### ISSUE TITLE
Cannot access 'Response' before initialization on `deno bundle`

### ISSUE THREAD

**Issue by galiazzi** [denoland/deno#12086]
After upgrading to version 1.14 this error happened when using `deno bundle`

Example test.ts code:
```ts
import { Application } from "https://deno.land/x/oak@v9.0.0/mod.ts";

const app = new Application();

app.use((ctx) => {
  ctx.response.body = "Hello World!";
});

await app.listen({ port: 8000 });
```

Commads:
```bash
deno bundle test.ts out.js
deno run -A out.js
```

Error:
```
error: Uncaught ReferenceError: Cannot access 'Response' before initialization
const DomResponse = Response;
                    ^
```

Deno version
```
deno 1.14.0 (release, x86_64-apple-darwin)
v8 9.4.146.15
typescript 4.4.2
```

**Comment by MarkTiedemann** [comment]
Seems like Oak's Response class is colliding with the native Response API:

```typescript
export const DomResponse: typeof Response = Response;
```

https://github.com/oakserver/oak/blob/6f680c9350e0fd36b99de60aeaaa39552315d2d0/http_server_native.ts#L10

```typescript
export class Response { /* ... */ };
```

https://github.com/oakserver/oak/blob/6f680c9350e0fd36b99de60aeaaa39552315d2d0/response.ts#L130

Not sure why this happens.

As a temporary fix, you can replace the 2 occurences of " Response" with " OakResponse" (mind the leading space) in `out.js` and it will run just fine.

**Comment by kitsonk** [comment]
There were changes in swc for 1.14 to fix issues when locally named symbols that clashed with globally named symbols were being renamed unnecessarily, but it seems like when they are being imported and specifically renamed not to shadow the globals, it breaks.

So i need to isolate the issue better and raise it with swc.

**Comment by jtoppine** [comment]
Just FYI, this appears to still be an issue with 1.14.2. I believe deno.land/x/canvas suffers from this issue as well as oak. (has swc been updated for this release? _i think_ there have been some commits on the swc repo that could potentially contain a fix for this, I don't know how to test that, though)

**Comment by kitsonk** [comment]
It wasn't updated for 1.14.2. I will check to see if swc updates have fixed it though.

**Comment by Noxdor** [comment]
@kitsonk Could you a give us a brief update on this issue? Is there progress in fixing it? Is there a way to help with doing so?

**Comment by jaredkrinke** [comment]
At least in my case, this bug is fixed in a newer version of swc (1.2.102+). It sounds like someone is actively working on upgrading the version of swc used in Deno.

More info:

In my case (which I believe is the same situation as in this bug), I ran swc's spack command manually and found that the version built into Deno 1.16.2 (swc bundler 0.75.0, from swc 1.2.101) exhibited this problem.

The very next release of swc (swc bundler 0.75.1 from swc 1.2.102) fixed my issue. I also confirmed this issue remained fix on the latest release: @swc/core@1.2.112.

Note that I don't know how Deno configures swc, so I'm not sure if it's possible to bundle something up yourself using swc directly (without Deno) and then have it work with `deno compile`.

**Comment by Pjort** [comment]
I can confirm the problem still exists when using `deno compile` with windows target.

Deno version: 1.16.4 (release, x86_64-pc-windows-msvc)
Oak version: 10.0.0

**Comment by rabbitkiller-dev** [comment]
deno run -A mod.js
```
error: Uncaught ReferenceError: Cannot access 'Response' before initialization
const DomResponse = Response;
```

![image](https://user-images.githubusercontent.com/28952169/145551046-0bfec7b3-ee4d-42d5-b82d-47e9c51c34df.png)

```
Deno 版本：1.16.4（发布，x86_64-pc-windows-msvc）
Oak 版本：10.0.0
```

**Comment by kitsonk** [comment]
@rabbitkiller-dev the fix is not in 1.16.4.  You need to either use the canary release or wait until 1.17.0 next week.  We close issues when the fix is merged into main, not when it becomes part of a release.

**Comment by emrul** [comment]
I have tried the latest Deno release (1.17.0) and also tried canary and I am facing what appears to be the same issue on my [script](https://github.com/Twingate/labs/blob/master/scripts/js/tg.js) - both with Deno bundle and Deno compile. The script works fine when executed via `deno run`.  I am not sure if the fact that I need `--unstable` is causing this?

Trying to the output of `deno bundle` gives me this:
```
error: Uncaught (in promise) ReferenceError: Cannot access 'NodeTypeError' before initialization
class ERR_INVALID_ARG_TYPE extends NodeTypeError {
                                   ^
    at file:///Users/...js/tg.bundle.js:12236:36
```
and indeed, I can see the class `NodeTypeError` is extended before it has been declared.

```
% deno --version
deno 1.17.0+ac06797 (canary, x86_64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
```

Any pointers would be greatly appreciated.

**Comment by bartlomieju** [comment]
@emrul please open a new issue and provide some reproduction code. This might actually be a problem in `deno_std/node`
