### ISSUE TITLE
Variable naming not correct for "var" in Deno.emit

### ISSUE THREAD

**Issue by dgreensp** [denoland/deno#12436]
I have a situation where bundling up a bunch of code with Deno.emit breaks, because a "var" in one module and a function in another are dumped into the same scope without renaming.

The `var` is in this code (which is immediately inside the outer function wrapper:

```js
    for(var i = 0, len = prefixedUnitlessProperties.length; i < len; ++i){
        var property = prefixedUnitlessProperties[i];
        unitlessProperties[property] = true;
        for(var j = 0, jLen = prefixes.length; j < jLen; ++j){
            unitlessProperties[getPrefixedProperty(prefixes[j], property)] = true;
        }
    }
```

while the function is this (also immediately inside the outer function wrapper):

```js
    function property(name, value) {
        return new LiveElementProperty(name, value);
    }
```

When some code goes to call the `property(...)` function, `property` resolves to the string `"order"` left over from the loop above instead of the function. :(

Perhaps variable renaming does not correctly take into account var scope?

**Comment by dsherret** [comment]
Reproduction code:

```ts
const result = await Deno.emit("file:///mod.ts", {
  bundle: "module",
  sources: {
    "file:///mod.ts": `
    import * as test from "./mod2.ts";
for (var i = 0; i < 10; i++) {
  var property = "test";
  console.log(property);
}

console.log(test.property(1, 2));
    `,
    "file:///mod2.ts": `
    export function property(a, b) {
      return a + b;
    }
    `
  },
});

console.log(result.files["deno:///bundle.js"])
```

Not a regression. Also occurs in old versions... tested 1.12-1.15.

Output:

```ts
function property(a, b) {
    return a + b;
}
for(var i = 0; i < 10; i++){
    var property = "test";
    console.log(property);
}
console.log(property(1, 2));
```

**Comment by lucacasonato** [comment]
This is fixed in Deno 1.15.3

**Comment by dgreensp** [comment]
It's not fixed for my case, unfortunately.  I'll see if I can create a repro.

**Comment by dgreensp** [comment]
I was going to post a reproduction involving a remote dependency, like this:

---

In file `./main.ts`:

```ts
import { property } from "./property.ts";

console.log(property());
```

In file `./property.ts`:

```ts
export { render } from "https://cdn.skypack.dev/fela-dom@11.7.0"; // breaks things!

export function property(): string {
  return "abc";
}
```

---

...but with a little more work I managed to boil it all the way down to a self-contained repro.

At the REPL (`deno repl --unstable`):

```ts
const result = await Deno.emit("file:///mod.ts", {
  bundle: "module",
  sources: {
    "file:///mod.ts": `
    import { property } from "./mod2.ts";

console.log(property());
    `,
    "file:///mod2.ts": `
    import { test } from "./mod3.ts";

    export function property(): string {
      return "abc";
    }
    
    test();
`,
    "file:///mod3.ts": `
export function test() {}

for (var i = 0; i < 10; i++) {
  var property = "test";
  console.log(property);
}
`,
  },
});

console.log(result.files["deno:///bundle.js"]);
```

Output:

```ts
function test() {
}
for(var i = 0; i < 10; i++){
    var property = "test";
    console.log(property);
}
function property() {
    return "abc";
}
test();
console.log(property());
```

This is with Deno 1.15.3.
