### ISSUE TITLE
bug: v1.16.0 --unstable option not working

### ISSUE THREAD

**Issue by gseok** [denoland/deno#12722]
- my code using ```const sig = Deno.signal('SIGINT');```
- and deno run code like this >> ```deno run --watch --allow-net --allow-read --unstable ./src/server.ts```
- I'm definitely using "--unstable" options.!!!

Try deno 1.16.0 (release, x86_64-apple-darwin) > failure running with follow output
```
error: TS2339 [ERROR]: Property 'signal' does not exist on type 'typeof Deno'. 'Deno.signal' is an unstable API. Did you forget to run with the '--unstable' flag?
  const sig = Deno.signal('SIGINT');
                   ~~~~~~
```

Try deno 1.15.3 > success running..!!!!

So... I think, this is a bug in 1.16.0. 
Please check this problem.

**Comment by bartlomieju** [comment]
`Deno.signal()` was replaced with `Deno.addSignalListener()` API; more info here: https://deno.com/blog/v1.16#new-unstable-signal-listener-api

It is indeed a bug that you see this suggestion and I will fix it shortly.

**Comment by authcompanion** [comment]
Still getting error in v1.16.2. Whats expected again? Ty for the info!

`TS2339 [ERROR]: Property 'signal' does not exist on type 'typeof Deno'.
    Deno.signal("SIGINT"),`

**Comment by bartlomieju** [comment]
@authcompanion this was fixed and released in v1.16.1, make sure to upgrade to the latest version

**Comment by authcompanion** [comment]
@bartlomieju odd I'm on the latest version and still get error:
`deno 1.16.2 (release, x86_64-apple-darwin)
v8 9.7.106.2
typescript 4.4.2`

Here's the snippet I'm using it in:
https://github.com/authcompanion/authcompanion/blob/a88626b1d6d08016987f612a51a92398e8c7a605/bin/server.ts#L26

error: TS2339 [ERROR]: Property 'signal' does not exist on type 'typeof Deno'.
    Deno.signal("SIGTERM"),
         ~~~~~~
    at file:////bin/server.ts:26:10

TS2339 [ERROR]: Property 'signal' does not exist on type 'typeof Deno'.
    Deno.signal("SIGINT"),
         ~~~~~~
    at file:///bin/server.ts:27:10

TS2339 [ERROR]: Property 'signal' does not exist on type 'typeof Deno'.
    Deno.signal("SIGABRT"),
         ~~~~~~
    at file:///bin/server.ts:28:10

Found 3 errors.

**Comment by bartlomieju** [comment]
@authcompanion as mentioned above - `Deno.signal` API was removed and replaced with `Deno.addSignalListener`/`Deno.removeSignalListener`.

**Comment by authcompanion** [comment]
@bartlomieju Got the API working thanks! 🙏
