### ISSUE TITLE
Property 'randomUUID' does not exist on type 'Crypto'

### ISSUE THREAD

**Issue by sant123** [denoland/deno#12754]
When using this settings:

``` jsonc
// deno.jsonc
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "dom.asynciterable", "deno.ns"]
  }
}
```

And this code:

``` ts
// mod.ts
const random = crypto.randomUUID();
```

Running `deno run --config deno.jsonc mod.ts` causes the following error:

```
error: TS2339 [ERROR]: Property 'randomUUID' does not exist on type 'Crypto'.
const random = crypto.randomUUID();
```

**Comment by kitsonk** [comment]
This is a challenge. The default libs from TypeScript do not yet include `crypto.randomUUID` and by supplying the lib, you are indicating that you want to type check against those "generic" browser libs, which do not include newer APIs like this (and notably Safari and iOS don't currently support it).

We really don't want to get into augmenting the default published DOM library for TypeScript. We do it for the ES libs, but that is already a challenge and risky.

The best solution at the moment would be to do a `declare global` in one of your modules to add it your global scope. I am mobile or I would provide a better example of how to do it.

**Comment by sant123** [comment]
It sounds reasonable, could you post an example of how to add it in the global scope please?

**Comment by sant123** [comment]
This is my workaround for now:

``` ts
declare global {
  interface Crypto {
    randomUUID: () => string;
  }
}

console.log(crypto.randomUUID());

export {};
```

![image](https://user-images.githubusercontent.com/7959437/142014297-7eeb67be-d758-4e88-bf31-a1b192694cc0.png)

Thanks @kitsonk !

**Comment by KyleJune** [comment]
This will get resolved in TypeScript 4.6 which is scheduled for release in February. The randomUUID type was just added for the 4.6 beta.

**Comment by vegerot** [comment]
Still doesn't look like it's there https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L3657-L3661

**Comment by KyleJune** [comment]
> Still doesn't look like it's there https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L3657-L3661

I may have misunderstood a PR that added `randomUUID` to `dom.generated.d.ts` in the `src/lib directory`. I thought that would mean it would be available for the dom lib.

https://github.com/microsoft/TypeScript/pull/47445#issuecomment-1015998057
 https://github.com/microsoft/TypeScript/blob/main/src/lib/dom.generated.d.ts#L3632

**Comment by KyleJune** [comment]
> Still doesn't look like it's there https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L3657-L3661

Looks like maybe I was right that it will be fixed when deno upgrades to TypeScript 4.6. if you switch from main branch to the v4.6.2 tag, it is in `lib.dom.d.ts`.

https://github.com/microsoft/TypeScript/blob/v4.6.2/lib/lib.dom.d.ts#L3652

**Comment by growlytics** [comment]
`window.crypto['randomUUID']();`

Try this, I avoided the same error with this snippet.

**Comment by vegerot** [comment]
@growlytics thanks.  I know that's a workaround, but the real bug this is reporting is that this type doesn't exist on global

**Comment by jeronimoek** [comment]
I don't know if this has to do with deno, but since this is one of the first results for this error in general:
This works for me in React:
`npm i @types/node@14.17.34`

**Comment by vegerot** [comment]
@jeronimoek it doesn't, but thank for the help! c:

**Comment by pencilcheck** [comment]
It doesn't have randomInt either. I'm surprised.

**Comment by petamoriken** [comment]
@pencilcheck `crypto.randomInt` is not a web standard, it's [a non-standard extension of Node.js](https://nodejs.org/api/crypto.html#cryptorandomintmin-max-callback). You can use it from `node:crypto`.

```ts
import crypto from "node:crypto";

console.log(crypto.randomInt(10));
```
