### ISSUE TITLE
Not possible to debug worker

### ISSUE THREAD

**Issue by jonek** [denoland/deno#13572]
It seems the debugger in VSCode and Chrome never stops at breakpoints in worker code.

Are there any variables, specific Deno command line flags or worker options I have to use to be able to debug worker code?

**Comment by jonek** [comment]
This is the `main.js` I used:
```
console.log('main: started');
debugger;
const myWorker = new Worker(new URL("./worker.js", import.meta.url).href, { type: "module" });
console.log('main: spawned', myWorker);
```

This is the `worker.js`:
```
try {
    console.log('worker: hello from worker');
    debugger;
 } catch(e) {
    console.error('error', e);
}
```

I also found this: https://github.com/denoland/deno/blob/1fb5858009f598ce3f917f9f49c466db81f4d9b0/runtime/web_worker.rs#L448

It seems to indicate, that the inspector will never stop in worker code.

I launched Deno with `--inspect-brk`.

VSCode was showing either the output of the main worker or the output of the worker in the debugger view. It seemed to choose either one indeterministically.

**Comment by bartlomieju** [comment]
@jonek that flag only indicates that debugger shouldn't break on the first line of worker code. I will verify how it works in VSCode, but in Chrome Devtools (`chrome://inspect`) once the worker is launched you will see a new entry show up that allows you to connect to it.

**Comment by vazexqi** [comment]
@bartlomieju - Any updates on this? Is this a limitation of deno? Or, of the deno VS Code extension?

I have only been able to get this to work if I use it with the Chrome Devtools (`chrome://inspect`) but I was hoping to have it work inside VS Code.

<img width="1912" alt="Screen Shot 2022-08-26 at 11 11 49 AM" src="https://user-images.githubusercontent.com/54414/186967059-40246d6c-64d1-49dc-b58e-b985ff5f8ce1.png">

**Comment by bartlomieju** [comment]
This is something I will be tackling in October as I'm OOO for the next two weeks.

**Comment by bartlomieju** [comment]
FYI I'm investigating this issue - it turned out to be much more complex than I expected. The way it works for Node is by using a custom "NodeWorker" domain for Chrome Devtools Protocol that is not really standardized. I will try to get in touch with VSCode team to see if there's a way forward to make it work more like in browser, if that won't be possible we'll look into using the same mechanism as Node does.

**Comment by ntotten** [comment]
Anyone interested in working on this on a sponsored basis? This is a major annoyance, but I’m not at all familiar with the internals at this level so I’d be willing to fund this work. Let me know.

**Comment by jespertheend** [comment]
I managed to trigger a breakpoint from code run in a worker.
- In `chrome://inspect/#devices` I clicked 'inspect' below 'deno - worker-0'
- Then I opened the file I wanted to debug in the inspector
- A notification popped up stating 'This script is on the debugger's ignore list'
- I clicked 'Remove from ignore list' which seems to untoggle the 'Content scripts injected by extensions' preference
- Then I placed my breakpoint and the debugger paused once it hit that breakpoint

**Comment by unit-404** [comment]
GIve me free fake WebWorker (jsut async in single thread) for debug. I'm really unable to debug that.

**Comment by mommysgoodpuppy** [comment]
To my surprise I found a workaround to get worker breakpoints to hit in VSCode. 
- Use a launch compound with an attach request to debug and "restart": false
- Have a wait to make sure debugger has time to attach to worker
- Use console.log inside worker onmessage which seems to be the only position where the debugger can bind?

Unfortunately this is still highly inconsistent, I think the debugger accidentally attaches to the same process twice a lot of the time. If anyone knows how to explicitly have the ports between main and workers be different or different ws addresses let me know. 
https://github.com/mommysgoodpuppy/DenoDebugWebworkersExample

**Comment by pmunin** [comment]
Any update on this with real fix?

The workarounds above don't seem to work for Worker created in test while debugging via deno codelense

**Comment by alex-controlx** [comment]
Using `chrome://inspect ` as described here https://docs.deno.com/runtime/fundamentals/debugging/ works.

Our app uses web workers for custom clients' scripts. We need to be able to attach an inspector to the `worker` only.

It would be great to have something like this:
```
{
  type: "module",
  deno: {
    inspector: true,
    permissions: {},
 },
```

as the options in `new Worker`

**Comment by bartlomieju** [comment]
Work that should make it possible has started in https://github.com/denoland/deno/pull/30743 and https://github.com/denoland/deno_core/pull/1193.

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/pull/31527 and will be released in v2.6.2.

**Comment by tsalsa919** [comment]
Hey what is the status of this atm? I am on deno 2.6.10 and still NOT able to put break point on Woker 

`const worker = new Worker(
  new URL("./worker.ts", import.meta.url).href,
  {
    type: "module",
  },
);`

Or are we just sticking to using `--unstable-worker-options` in deno for now?

**Comment by bartlomieju** [comment]
@tsalsa919 this is now fixed. If you are experiencing problems on latest version (2.6.10) please open a new issue with description of the problem.
