### ISSUE TITLE
Fetching remote module efficiency

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#1533]
Deno should respect cache headers and the [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) tag header when fetching remote modules.  ETag could allow Deno to "stat" a remote module to see if it needs to be retrieved.

Also, Deno should possibly support gzip and brotli content encoding of resources to reduce bandwidth when retrieving remote modules.  This would require the ability to decode gzip and brotli in Rust.

**Comment by bartlomieju** [comment]
FYI, all of described functionality can be relatively easily added to our current setup.
- `gzip` - requires only activation when [building HTTP client](https://docs.rs/reqwest/0.10.0/reqwest/struct.ClientBuilder.html#method.gzip)
- `brotli` - can be easily integrated into HTTP client using [`async_compression`](https://docs.rs/async-compression/0.2.0/async_compression/) crate
- `ETag` - can be intercepted from request headers

I think we could safely enable `gzip` and `brotli` compressions for all requests, checking of `ETag` should be done in `cli/file_fetcher.rs`. All in all I say it's "good first issue" in Rust.

CC @GaryPWhite you were looking for some new PRs, this might be interesting

**Comment by kitsonk** [comment]
Also agree with the `ETag`, I had thought about that a long time ago.  It sort of substantially changes the logic though @bartlomieju as currently we don't check invalidation of remote modules at all, right?  It is a good thing, but it won't "improve" performance, it will actually slow down what we currently have.  Also we would need to cache the `ETag` and fetch it out of the cache.  I am not sure it is a "good first issue" given those things and likely should be a seperate issue all together (around caching and invalidation of remote modules).

**Comment by kitsonk** [comment]
I am not so convinced it is a good first issue, as it is fairly complex change to the logic, as we do no cache checking/invalidation of remote modules at the moment.  Though if someone wanted to try, I am sure we would all be glad to help support.

**Comment by manyuanrong** [comment]
I'd like to try that

**Comment by manyuanrong** [comment]
We have cached the entire script file, do we still need to use etag? Or when should we use etag?

**Comment by bartlomieju** [comment]
> We have cached the entire script file, do we still need to use etag? Or when should we use etag?

When you run `deno --reload` then on-disk cache is ignored and all remote files are downloaded. 

What we want to do is save `ETag` header from response to `headers.json` file (just like we do with content-type, see code snippet below) and then if you run with `deno --reload` we don't want to blindly download **all** remote files, but only those whose `ETag` headers has changed.

https://github.com/denoland/deno/blob/c41280a057c9ca300afe43f2cb4f576e050f8cde/cli/file_fetcher.rs#L424-L433

**Comment by bartlomieju** [comment]
Fixed in  1ea06f9

**Comment by kitsonk** [comment]
Awesome contribution @manyuanrong

**Comment by manyuanrong** [comment]
Thank you, @kitsonk . Thanks to @bartlomieju 's help, but still not perfect, I will try my best to do better.
