### ISSUE TITLE
lsp: Code autocompletion stops working in WebStorm with Deno (Windows only)

### ISSUE THREAD

**Issue by makovkins** [denoland/deno#15805]
I am using the latest canary build of Deno with WebStorm WS-222.3739.57 and the official Deno plugin on Windows 11. Code autocompletion stops working and the only thing to make it work again is restart the editor. 

I opened a WebStorm issue but their team says that it's a Deno bug. The detailed explanation of the issues and steps how to reproduce it are there:
https://youtrack.jetbrains.com/issue/WEB-57101

Here is a simple project that you need to reproduce the bug:
[webstorm-bug.zip](https://github.com/denoland/deno/files/9506862/webstorm-bug.zip)

Open index.ts, type "state." in function body and autocompletion will break. See the detailed instruction inside index.ts file.
Btw, if you remove the import map, it will work as expected. So it's something wrong with the import map.

The error occurs because of an incorrect Content-Length in a reply received from the deno. There are non ASCII characters in the reply and the length is computed incorrectly.

The issues is very similar to this one that is already fixed but it doesn't fix the problem with WebStorm:
https://github.com/denoland/deno/issues/15781

The bug might be reproduced on windows only! Don't try to reproduce it on MacOS/Linux.

**Comment by littledivy** [comment]
Which server are we talkiing about here? Is WebStorm using the unstable `Deno.serve` API or `std/http/server.ts`? The `Content-Length` issue was fixed in `Deno.serve` in 1.25.2

**Comment by makovkins** [comment]
I already updated to deno 1.25.2 and the issue with WebStrom still exists. It was the suggestion of JetBrains team that it's a Content-Length bug. Possibly it is not. In detailed log files I see that the string is truncated:
![image](https://user-images.githubusercontent.com/27928426/189354324-2e60b74a-9a93-47e7-a50b-02f420b24475.png)

The issue is reproduced with ease if you open my sample project [webstorm-bug.zip](https://github.com/denoland/deno/files/9506862/webstorm-bug.zip) and follow the instuctions in index.ts.

**Comment by kitsonk** [comment]
@littledivy it is likely a bug with tower, which is what provides the server for the lsp.

We should see a similar issue in vscode on windows, though maybe vscode handles it more gracefully.

**Comment by makovkins** [comment]
> We should see a similar issue in vscode on windows, though maybe vscode handles it more gracefully.
Tested it with VSCode on Windows, autocompletion works perfectly...

**Comment by kitsonk** [comment]
Hmmm that is very strange, though it could be that vscode ignores the content-length. 😕

**Comment by makovkins** [comment]
Any news on that? The issue still exists and easily reproduced. It is very annoying!

**Comment by lucacasonato** [comment]
We have not gotten another report of this in 2 years now, so I am tentatively assuming this has been fixed in the mean time.
