### ISSUE TITLE
Progress bar conflicts with permission prompt

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#16860]
Given the following script and a clean $DENO_CACHE/deps folder:

```ts
// main.ts
const url = "https://deno.land/x/ts_morph/mod.ts"
const test = await import(url);
```

```
> deno run main.ts
✅ Granted net access to "deno.land".
Download ⠹ https://deno.land/x/ts_morph/mod.ts
Warning Implicitly using latest version (17.0.1) for https://deno.land/x/ts_morph/mod.ts
Download ⠹ https://deno.land/x/ts_morph@17.0.1/mod.ts
⚠️  ┌ Deno requests net access to "deno.land".
   ├ Run again with --allow-net to bypass this prompt.
Download ⠸ https://deno.land/x/ts_morph@17.0.1/mod.ts
```

The permission prompt should disable any progress bars.

**Comment by sigmaSd** [comment]
You can run with `--reload` instead of cleaning the cache

**Comment by sigmaSd** [comment]
I thought it was fixed https://github.com/denoland/deno/issues/16253 but seems not

**Comment by dsherret** [comment]
I was trying to find that issue when I opened this one. Yeah, it still exists.
