### ISSUE TITLE
`npm:supports-color` doesn't give the right values in deno

### ISSUE THREAD

**Issue by ry** [denoland/deno#18665]
```js
import supportsColor from "npm:supports-color";

console.log(supportsColor)

if (supportsColor.stdout) {
  console.log("Terminal stdout supports color");
}

if (supportsColor.stdout.has256) {
  console.log("Terminal stdout supports 256 colors");
}

if (supportsColor.stderr.has16m) {
  console.log("Terminal stderr supports 16 million colors (truecolor)");
}
```

**Comment by sigmaSd** [comment]
On linux it just outputs stdout: false stderr:false
If you add `console.log(env) ` after `const { env } = process;` in index.js of supports-color, suddenly it works correctly and outputs the expected result:

```
{
  stdout: { level: 3, hasBasic: true, has256: true, has16m: true },
  stderr: { level: 3, hasBasic: true, has256: true, has16m: true }
}
```

It seems like node:process is not able to call into Deno env automatically unless "provoked?" with something like logging it into stdout

```
deno 1.32.4 (release, x86_64-unknown-linux-gnu) wezterm
```

**Comment by kt3k** [comment]
We disabled permission prompt when accessing `process.env.<prop>` in https://github.com/denoland/deno_std/pull/3178 because otherwise so many permission prompts appear while using common npm modules

**Comment by gliheng** [comment]
I see, but the behavior looks like bug, maybe it's better to print some useful hint in that case. I'll close the PR then.

**Comment by kt3k** [comment]
Maybe it's worth considering to enable it again as `A = allow all` option is available in permission prompt now (added in #17140). Core team will discuss this soon

**Comment by itsajay1029** [comment]
Can I work on this issue @kt3k @ry ? Please assign it to me if I can

**Comment by scarf005** [comment]
I ran the script on Ubuntu and all four logs are correctly showing as expected, and its outputs are identical when executed via node as well. Maybe could this mean that the issue is now resolved?

```
{
  stdout: { level: 3, hasBasic: true, has256: true, has16m: true },
  stderr: { level: 3, hasBasic: true, has256: true, has16m: true }
}
Terminal stdout supports color
Terminal stdout supports 256 colors
Terminal stderr supports 16 million colors (truecolor)
undefined
```

```
os: ubuntu 23.04
shell: fish 3.6.0
terminal: konsole (x-terminal-emul)
deno 1.34.3 (release, x86_64-unknown-linux-gnu)
v8 11.5.150.2
typescript 5.0.4
```

**Comment by sigmaSd** [comment]
This bug still exists
here is a simple example

**a.ts**
```ts
import which from "npm:which";
console.log(await which("ls", { nothrow: true }));
```
if `deno run a.ts` is used , this will return null

it only work if `--allow-env` is passed

**Comment by itsajay1029** [comment]
@kt3k Please check the PR
