### ISSUE TITLE
Deno / Node(Vite?) issue - Uncaught Error: EINVAL: invalid argument, stat

### ISSUE THREAD

**Issue by sortofsleepy** [denoland/deno#19067]
👋 

Attempted to try to start a project today with [create-vite-extra](https://github.com/bluwy/create-vite-extra). Initially ran into an issue with esbuild that required an upgrade to Deno. However, after doing so, I am still having trouble. 
It was suggested that I open the issue here so here I am. 

The issue is essentially: 

* after running `deno run -A npm:create-vite-extra`
* and going through the prompts, selecting one of the Deno templates
* and finally running `deno task dev`

I get the following error 

```
error: Uncaught Error: EINVAL: invalid argument, stat
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:89:11)
    at __node_internal_uvException (ext:deno_node/internal/errors.ts:182:12)
    at denoErrorToNodeError (ext:deno_node/internal/errors.ts:1826:16)
    at ext:deno_node/_fs/_fs_stat.ts:83:97
    at eventLoopTick (ext:core/01_core.js:181:11)
```

* I am on Windows
* Node is `v18.16.0`
* Deno is 

```
deno 1.33.2 (release, x86_64-pc-windows-msvc)
v8 11.4.183.1
typescript 5.0.3
```

**Comment by bartlomieju** [comment]
That might be related to https://github.com/denoland/rusty_v8/issues/1226

**Comment by KoenHaagsma** [comment]
Got the same issue.

**Comment by kylesloper** [comment]
Yep same here :(

**Comment by ifrvn** [comment]
Same here in deno 1.33.3 & v8 11.4.183.2

**Comment by tiborsaas** [comment]
I have the very same problem on windows 10:

`deno 1.33.3 (release, x86_64-pc-windows-msvc)`

`node v14.17.0`

**Comment by bartlomieju** [comment]
Thanks for the reports, I will debug and fix it for Deno v1.33.4.

**Comment by bartlomieju** [comment]
As a work around you can downgrade Vite to 4.2.0 in the meantime. See linked Vite issue above for more details.

**Comment by patak-dev** [comment]
vite@4.3.7 should fix this issue, thanks for the heads up @bartlomieju

**Comment by bartlomieju** [comment]
I'm gonna close this issue for now. Let me know if the problem appears again.

**Comment by hansSchall** [comment]
The bug still exists (Deno 1.42.4)

Downgrading to Vite 4.2.0 fixed it for me.

**Comment by hansSchall** [comment]
To me it seems like Deno behaves differently than Node when the file path is malformed.

I was able to use vite@^5.0.0 when I ensured to inject my own loader (which is using paths with custom url schemes) before vite tries to resolve the import using the default fs loader.
