### ISSUE TITLE
Unable to find napi_register_module_v1 on mac m1

### ISSUE THREAD

**Issue by VelinGeorgiev** [denoland/deno#20071]
I am having a hard time installing sharp npm module with Deno. I am currently using Deno 1.36 and mac m1 chip, also following the steps from sharp [https://github.com/lovell/sharp/issues/2583](https://github.com/lovell/sharp/issues/2583), but I am getting the error below.

```
error: Uncaught Error: 
Something went wrong installing the "sharp" module

Unable to find napi_register_module_v1 symbol in /Users/velingeorgiev/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.32.4/build/Release/sharp-darwin-arm64v8.node

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (file:///Users/velingeorgiev/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.32.4/lib/sharp.js:37:9)
    at Object.<anonymous> (file:///Users/velingeorgiev/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.32.4/lib/sharp.js:40:4)
    at Module._compile (node:module:731:36)
    at Object.Module._extensions..js (node:module:745:12)
    at Module.load (node:module:656:34)
    at Function.Module._load (node:module:539:16)
    at Module.require (node:module:675:23)
    at require (node:module:789:20)
    at Object.<anonymous> (file:///Users/velingeorgiev/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.32.4/lib/constructor.js:11:1)
    at Object.<anonymous> (file:///Users/velingeorgiev/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.32.4/lib/constructor.js:441:4)
Watcher Process failed. Restarting on file change...
```

Is this by design, or will future support be provided?

**Comment by bartlomieju** [comment]
We want to have sharp working on Deno, it's surprising this error is raised. We need to check what mechanism sharp uses to register its native addon.

**Comment by birkskyum** [comment]
Hit this today as well

```sh
Task start deno run -A --node-modules-dir ./src/app.ts
error: Uncaught Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-darwin-arm64v8.node'
Require stack:
- /Users/admin/repos/regenworks-backend/node_modules/.deno/sharp@0.32.4/node_modules/sharp/lib/sharp.js
- /Users/admin/repos/regenworks-backend/node_modules/.deno/sharp@0.32.4/node_modules/sharp/lib/constructor.js
- /Users/admin/repos/regenworks-backend/node_modules/.deno/sharp@0.32.4/node_modules/sharp/lib/index.js
- /Users/admin/repos/regenworks-backend/node_modules/.deno/join-images@1.1.5/node_modules/join-images/lib/main.js
- /Users/admin/repos/regenworks-backend/node_modules/.deno/join-images@1.1.5/node_modules/join-images/lib/main.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scri
```

**Comment by birkskyum** [comment]
There is some related info here: https://github.com/lovell/sharp/issues/3750

**Comment by birkskyum** [comment]
Regarding the strong focus on security of Deno, the approach taken here by Bun to introduce a [list](https://github.com/oven-sh/bun/pull/4263/files) of [trustedDependencies](https://bun.sh/docs/cli/install#trusted-dependencies), instead of having the more insecure `postinstall` npm lifecycle script etc. might somehow be of interest to Deno as well.

**Comment by bartlomieju** [comment]
Hey @VelinGeorgiev, @littledivy and I just did some digging into this issue. We used Deno v1.36.3 and this script:
```js
import sharp from "npm:sharp";

const semiTransparentRedPng = await sharp({
  create: {
    width: 48,
    height: 48,
    channels: 4,
    background: { r: 255, g: 0, b: 0, alpha: 0.5 }
  }
})
  .png()
  .toBuffer();

Deno.writeFileSync("semi-transparent-red.png", semiTransparentRedPng);
```

The only problem we encountered was missing `.node` file (which appears is not distributed by `sharp`, but instead relies on the `install` script in the `sharp`'s `package.json file). Once we manually run that `install` script (eg. by using `npm run install` in the `./node_modules/sharp/` directory) it worked without a problem and wrote a PNG file with a red square. 

Could you provide a full reproduction on how you arrived at that error? As it stands out it appears to me that the problem is that Deno doesn't support "lifecycle" hooks as pointed out by @birkskyum. This is something we've discussed several times and haven't arrived at a good solution yet.

**Comment by VelinGeorgiev** [comment]
@bartlomieju I will give it a try with v1.36.3 and see if that will resolve the issue.

**Comment by birkskyum** [comment]
Could a list of "trustedDependencies" in deno.json and package.json similar to what bun introduced be a solution for deno as well, or are there other ideas? cli flags?

**Comment by lovell** [comment]
For those who haven't yet seen, the latest sharp v0.33.0 now provides full support for Deno.

**Comment by devsnek** [comment]
This should be fixed in https://github.com/denoland/deno/pull/24101, let us know if you run into more problems.

**Comment by brc-dd** [comment]
@devsnek I just tested with https://dl.deno.land/canary/e3b2ee183bc7497ec0432bc764678f5eda6495a7/deno-aarch64-apple-darwin.zip and `@parcel/watcher` is still failing (see my comment above for MRE). The error message is similar:

```ts
Watcher File change detected! Restarting!
error: Uncaught (in promise) TypeError: Unable to find register Node-API module at /Users/divyansh/Library/Caches/deno/npm/registry.npmjs.org/@parcel/watcher-darwin-arm64/2.4.1/watcher.node
    at Object.Module._extensions..node (node:module:776:20)
    at Module.load (node:module:654:32)
    at Function.Module._load (node:module:522:12)
    at Module.require (node:module:673:19)
    at require (node:module:787:16)
    at Object.<anonymous> (file:///Users/divyansh/Library/Caches/deno/npm/registry.npmjs.org/@parcel/watcher/2.4.1/index.js:15:13)
    at Object.<anonymous> (file:///Users/divyansh/Library/Caches/deno/npm/registry.npmjs.org/@parcel/watcher/2.4.1/index.js:43:4)
    at Module._compile (node:module:729:34)
    at Object.Module._extensions..js (node:module:743:10)
    at Module.load (node:module:654:32)
```

**Comment by devsnek** [comment]
Oops sorry, this got wrapped up into other `sharp` issues i was closing :smile: Have not verified this on macos yet.

**Comment by brc-dd** [comment]
This can be closed I guess. The original issue with sharp was fixed earlier and the issue with `@parcel/watcher` is from not calling `binding.unsubscribe` on `unload`. (That still fails because of https://github.com/denoland/deno/issues/12653 but it's unrelated to this.)
