### ISSUE TITLE
AOT build task SQL error

### ISSUE THREAD

**Issue by Marcisbee** [denoland/deno#20196]
_Edit: This happens using deno fresh._

I have a setup where github action caches dependencies and sends files to my server. Then restarts app.

Now since AOT I tought I can build the assets together with caching dependecies in this github action. So this is part of my action config now:
```yml
...

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: "1.36.1"

    - name: Caching deno dependencies
      run: |
        deno task build
      env:
        DISCORD_CLIENT_ID: test
        DISCORD_CLIENT_SECRET: test
        DENO_DIR: ./.cache
        CI: true

...
```

This is the response that I get, it seem to hang on some error related to sqlite. Not sure what is that. I do use `--unstable` flag and 
very tiny bit of `Deno.openKv()` and `import { Database } from "https://deno.land/x/sqlite3@0.9.1/mod.ts"` in this app.

```sh
Run deno task build
  deno task build
  shell: /usr/bin/bash -e {0}
  env:
    DISCORD_CLIENT_ID: test
    DISCORD_CLIENT_SECRET: test
    DENO_DIR: ./.cache
    CI: true
Task build deno run -A --unstable src/dev.ts build

...

The manifest has been generated for 8 routes and 4 islands.

...

Download https://deno.land/std@0.176.0/path/_constants.ts
Download https://deno.land/std@0.176.0/path/_util.ts
Download https://deno.land/std@0.176.0/_util/asserts.ts
Download https://deno.land/std@0.176.0/fs/_util.ts
error: Uncaught (in promise) Error: table queue already exists in 
create table queue (
  ts integer not null,
  id text not null,
  data blob not null,
  backoff_schedule text not null,
  keys_if_undelivered blob not null,

  primary key (ts, id)
);
create table queue_running(
  deadline integer not null,
  id text not null,
  data blob not null,
  backoff_schedule text not null,
  keys_if_undelivered blob not null,

  primary key (deadline, id)
);
 at offset 14: Error code 1: SQL error or missing database at ext:deno_kv/01_db.ts:8:17
  const manifest = (await import(toFileUrl(manifestPath).href))
                    ^
    at async build (https://deno.land/x/fresh@1.4.2/src/dev/build.ts:10:21)
    at async dev (https://deno.land/x/fresh@1.4.2/src/dev/dev_command.ts:38:5)
    at async file:///home/runner/work/puzzle/puzzle/src/dev.ts:5:1
Error: Process completed with exit code 1.
```

This is my build task `"deno run -A --unstable src/dev.ts build"`. One thing that is not default is that I moved it to `src/` folder following docs.

This task works fine when I do it on macbook m1, it just fails on github action `ubuntu-latest`. Not sure if this is enough info to find where the problem lies.

**Comment by losfair** [comment]
This should be fixed in https://github.com/denoland/deno/commit/0960e895da1275792c1f38999f6a185c864edb3f. Can you try with Deno 1.36.3?

**Comment by Marcisbee** [comment]
> This should be fixed in [0960e89](https://github.com/denoland/deno/commit/0960e895da1275792c1f38999f6a185c864edb3f). Can you try with Deno 1.36.3?

I don't see this particular error, but it still doesnt complete the process.

In about 20s CLI reports dependency download list and ends with this:
```sh
...
Download https://esm.sh/v131/@preact/signals-core@1.2.3/X-ZS8q/denonext/signals-core.mjs
Download https://esm.sh/v131/@preact/signals-core@1.2.3/X-ZS8q/dist/signals-core.d.ts
```

Nothing ever happens after these lines, no error, no progress, nothing.. I let it run for another 5 minutes and nothing ever happened. Seems like it just hung with no error.

**Comment by Marcisbee** [comment]
I'm closing this as original issue with the error posted in the issue was resolved.

Since there's no change regarding process freeze instead of the error (and I've tried many deno & fresh versions since) I decided I don't really care about the freeze as I'm switching away from Fresh.
