### ISSUE TITLE
Application does not show up with `deno compile --no-terminal`

### ISSUE THREAD

**Issue by windchime-yk** [denoland/deno#21091]
Thank you for the wonderful option called `--no-terminal`.
However, in my environment, the application did not show up after compile. I think this is the cause of this part, because it does not work when I add `--no-terminal`.

## Development environment
```bash
$ uname -sr
Linux 5.15.90.1-microsoft-standard-WSL2

$ deno --version
deno 1.38.0 (release, x86_64-unknown-linux-gnu)
v8 12.0.267.1
typescript 5.2.2
```

## Operating Environment
```powershell
> Get-ComputerInfo | select WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer

WindowsProductName WindowsVersion OsHardwareAbstractionLayer
------------------ -------------- --------------------------
Windows 10 Home    2009           10.0.19041.3636
```

## Verification Repository
https://github.com/rwl-dev-playground/verify-deno-webview

In the main branch, there is no `--no-terminal`.
In the no-terminal branch, there is `--no-terminal`.
Each can be executed with `deno task compile:windows`.

**Comment by cunev** [comment]
Downgrade to 1.36.0 for a temporary fix.

**Comment by Cedar-81** [comment]
Is there a way to fix this in the current version?

**Comment by windchime-yk** [comment]
We have checked and it seems that the application is show up on macOS even if `--no-terminal` is used.
The following is a list of the verification results for each environment.

- Windows 10(Deno v1.36.0) : does not show up
- Windows 10(Deno v1.39.0) : does not show up
- macOS Monterey(Deno v1.36.0) : show up
- macOS Monterey(Deno v1.39.0) : show up
- Ubuntu on WSL 2(Deno v1.36.0) : does not show up
- Ubuntu on WSL 2(Deno v1.36.0) : does not show up

I checked with the validation repository listed in the first Issue comment. The compile command is `deno task compile:windows`.

## Verification environment(macOS)
The Windows 10 and WSL 2 versions are listed in the first Issue comment and will be omitted, only the macOS versions will be listed.

``` zsh
% sw_vers
ProductName:    macOS
ProductVersion: 12.7
BuildVersion:   21G816

% deno --version              
deno 1.39.0 (release, x86_64-apple-darwin)
v8 12.0.267.8
typescript 5.3.3
```

**Comment by felipecrs** [comment]
I have the exact the same issue. Now I wonder if this is an issue with Deno or https://github.com/wobsoriano/deno-systray.

Can be easily reproduced with:

```console
$ deno compile -A https://github.com/wobsoriano/deno-systray/blob/dc21cf5b71fd68789d1db8f647ad805b5bc8cd51/example/index.ts

$ .\example.exe
<first confirm it works>

$ deno compile -A --no-terminal https://github.com/wobsoriano/deno-systray/blob/dc21cf5b71fd68789d1db8f647ad805b5bc8cd51/example/index.ts

$ .\example.exe
<confirm it doesn't work, the application closes immediately>
```

Can we get some support from Deno team? This would enable me to do some cool things.

**Comment by PAStheLoD** [comment]
To try to help with debugging I built deno (f57745fe, because later ones have a [bug](https://github.com/denoland/deno/issues/24874)) on Windows, and tried different PE subsystems. 3 works as usual (opens a terminal), 2 does not as reported.

(Basically edited [this line](https://github.com/denoland/deno/pull/17991/files#diff-fc607f903b2dfca3e91ceef543a99b74214ee727e19b472384a2c084d5a9da1bR613)... put in a hack to read an env var so it's easy to try different values.)


Probably it's not enough to simple set the subsystem the binary needs to be [linked](https://doc.rust-lang.org/reference/runtime.html#the-windows_subsystem-attribute) as such. And it might be even better to have the option to "[hide the console window](https://stackoverflow.com/a/29764309/44166)" at runtime, which means this can be a CLI argument for the compiled executable.

**Comment by cspotcode** [comment]
Minimal reproduction: compile and run a one-line deno script that writes `args[0]` to a file.  This way, it does not rely on any dependencies and does not use any stdio or terminal IO.

```
# Powershell
> echo 'Deno.writeTextFileSync("output.txt", Deno.args[0]);' > main.ts
> deno run -A ./main.ts foo
> cat output.txt
foo
> deno compile -A -o main-with-terminal.exe ./main.ts
> deno compile --no-terminal -A -o main-no-terminal.exe ./main.ts
> ./main-with-terminal.exe bar
> cat output.txt
bar
> ./main-no-terminal.exe biff
> cat output.txt
bar
# The no-terminal executable did not write to the file!
```

**Comment by svefro** [comment]
could not get --no-terminal to work so i made this https://jsr.io/@svefro/win-console-window-state

**Comment by felipecrs** [comment]
> could not get --no-terminal to work so i made this [jsr.io/@svefro/win-console-window-state](https://jsr.io/@svefro/win-console-window-state)

Thank you very much for writing it. I tested it, and indeed it hides the console window when called. Too bad it's still shown for some moments.

**Comment by KimLindblom** [comment]
I too struggle with this in Deno, so +1 to getting some eyes on it.

However svefro's solution does not appear work for me, even when running the provided example as-is the window merely minimizes itself (rather than actually hiding as advertised) and then the library console.logs out "false".

**Comment by Drakim** [comment]
I too struggle with this in Deno, so +1 to getting some eyes on it.

However svefro's solution does not appear work for me, even when running the provided example as-is the window merely minimizes itself (rather than actually hiding as advertised) and then the library console.logs out "false".

**Comment by svefro** [comment]
> I too struggle with this in Deno, so +1 to getting some eyes on it.
> 
> However svefro's solution does not appear work for me, even when running the provided example as-is the window merely minimizes itself (rather than actually hiding as advertised) and then the library console.logs out "false".

Default terminal on windows 10/11 needs to be set to 'Windows Console Host' or you can "Run as administrator" this always uses 'Windows Console Host'

Did you do that?

**Comment by Drakim** [comment]
Ah, I apologize, I did not.
When I tried "Run as administrator" it does indeed work and the console is invisible. However, this isn't a great solution for distributing as I don't want to tell my users to do that. 🥲

**Comment by svefro** [comment]
did a minor change.
method 1 works for me on windows 11
method 2 works for me on windows 10

can you try to run this `deno run -A https://jsr.io/@svefro/win-console-window-state/0.1.11/mod.ts`?
and report if the window is hidden on method 1?
Are you on windows 11?

**Comment by Drakim** [comment]
Thank you for the update.

I am on Windows 11, and when I run `deno run -A https://jsr.io/@svefro/win-console-window-state/0.1.11/mod.ts` the first method does indeed hide the console properly, while it is merely minimized for method 2.

**Comment by svefro** [comment]
👌

**Comment by Reububble** [comment]
I discuss a workaround in https://github.com/denoland/deno/issues/13107#issuecomment-2597301636

**Comment by thomas3577** [comment]
> could not get --no-terminal to work so i made this https://jsr.io/@svefro/win-console-window-state

This tool has a closed source?

**Comment by svefro** [comment]
> > could not get --no-terminal to work so i made this https://jsr.io/@svefro/win-console-window-state
> 
> This tool has a closed source?

No the source can be seen on JSR. https://jsr.io/@svefro/win-console-window-state/0.2.1/mod.ts

**Comment by Tentacola** [comment]
Pretty sure this is now fixed after #29144 got merged and can be closed

**Comment by felipecrs** [comment]
Maybe it's an issue with [deno-systray](https://github.com/wobsoriano/deno-systray), but this still doesn't work:

```console
~ ❯ deno -V
deno 2.3.5
~ ❯ deno compile -A --no-terminal https://deno.land/x/systray/example/index.ts
~ ❯ & .\example.exe
```

https://github.com/user-attachments/assets/10450445-e3af-4bc9-98f6-feb33889e9e5

**Comment by felipecrs** [comment]
Nevermind! This is indeed an [issue with deno-systray](https://github.com/wobsoriano/deno-systray/issues/6), and now Deno itself seems working great with `--no-terminal`. Thanks a lot for the fix!

**Comment by bartlomieju** [comment]
Fixed by #29144 (shipped in Deno 2.3.5). Confirmed working by @JasperVanEsveld and @felipecrs in the thread above; the remaining `--no-terminal` failure @felipecrs hit was traced to a bug in [deno-systray](https://github.com/wobsoriano/deno-systray/issues/6), not Deno itself.

Closing as resolved.
