### ISSUE TITLE
Deno.serve request.signal don't work

### ISSUE THREAD

**Issue by drag0n-app** [denoland/deno#21590]
Version: deno 1.39.0 (release, aarch64-apple-darwin)

```ts
Deno.serve({ port: 1000}, async (req) => {
  req.signal.onabort = (event: Event) => {
      console.log('canceled')
  }
  const res = await fetch('https://github.com/denoland/deno/releases/download/v1.39.0/deno-aarch64-apple-darwin.zip', {
    signal: req.signal
  });
  return res;
});
```

Started server, interrupted request, no abort signal Event

**Comment by littledivy** [comment]
Duplicate of https://github.com/denoland/deno/issues/10829

**Comment by mmastrac** [comment]
Fixed by https://github.com/denoland/deno/pull/23425

**Comment by tmkx** [comment]
the snippet still does not work on macOS arm64 with Deno v1.43.1. (https://github.com/denoland/deno/issues/21653)

### Deno v1.43.1 (unexpected)

```tsx
Deno.serve(async (request) => {
  request.signal.addEventListener('abort', () => console.log('cancelled'));
  console.log('signal 1', request.signal.aborted, new Date()); // expect false
  await new Promise((resolve) => setTimeout(resolve, 3000)); // abort during waiting
  console.log('signal 2', request.signal.aborted, new Date()); // expect true
  return new Response('Welcome to Deno!');
});
```
output:
```
signal 1 false 2024-05-06T15:52:27.923Z
signal 2 false 2024-05-06T15:52:30.928Z
cancelled
```

### Bun v1.1.7 (expected)

```tsx
const server = Bun.serve({
  port: 8000,
  async fetch(request) {
    request.signal.addEventListener('abort', () => console.log('cancelled'));
    console.log('signal 1', request.signal.aborted, new Date()); // expect false
    await new Promise((resolve) => setTimeout(resolve, 3000)); // abort during waiting
    console.log('signal 2', request.signal.aborted, new Date()); // expect true
    return new Response('Welcome to Bun!');
  },
});

console.log(`Listening on localhost:${server.port}`);
```
output:
```
signal 1 false 2024-05-06T15:55:01.673Z
cancelled
signal 2 true 2024-05-06T15:55:04.675Z
```

**Comment by bartlomieju** [comment]
@tmkx can you provide the full reproduction? I don't see where this signal is getting aborted.
