### ISSUE TITLE
[WPT] actions workflow wpt_epoch.yml is failing

### ISSUE THREAD

**Issue by panva** [denoland/deno#22257]
[Since Jan 26 2024 this workflow is failing](https://github.com/denoland/deno/actions/workflows/wpt_epoch.yml) and results are no longer submitted to wpt.fyi for aligned comparisons.

**Comment by bartlomieju** [comment]
Thanks for flagging this @panva, this should be fixed by https://github.com/denoland/deno/pull/22312.

**Comment by panva** [comment]
@bartlomieju #22312 did not resolve the issue, see https://github.com/denoland/deno/actions/runs/7823226371
