### ISSUE TITLE
`declare module` inside `.d.ts` does not get picked up by Deno

### ISSUE THREAD

**Issue by Mqxx** [denoland/deno#23007]
Hey, I currently have a problem when importing non js/ts files inside a js/ts file.  `deno-ts` shows an error with non-resolvable imports for non-js/ts files.

For example i have this `index.ts` files, somewhere in my project:

```ts
import styles from './hello_world.scss'
//     ^
//     Error: Module '"hello_world.scss"' has no default export. deno-ts(1192)
```
This behavior is correct because scss does not have a valid default export.

However, if I now create an index.d.ts file in the root of my project with the following content, the error still occurs. Deno simply ignores this file.

```ts
declare module '*.scss';
```
or
```ts
declare module '*.scss' {
  const content: string;
  export default content;
}
```
Neither of the two contents work. Also adding the `.d.ts` file to the `types` array in the `compilerOptions` did not help.

It would be really great if this error could be fixed or if this could be added as a feature.

- Deno version used: `1.41.3`

[Link](https://discord.com/channels/684898665143206084/1216692707569700964) to the discussion on discord.

**Comment by Mqxx** [comment]
Hey, any update on this? I am not sure if this is more a problem with the linter instead of deno itself.

**Comment by Mqxx** [comment]
https://github.com/denoland/deno/issues/23319

**Comment by greentore** [comment]
There's also an older (closed) issue: https://github.com/denoland/deno/issues/15132
Having to prefix fancy imports with `@ts-types` comments really sucks, but at least it works.

**Comment by strootje** [comment]
currently running on Deno 2.0.6. This is still an issue for me.

My two use cases are:
- unocss, having to import `virtual:uno.css`.
- imagetools, importing `*.*&imagetools`.

I used to just declare these in a custom types.d.ts. Now it's just errors :(

**Comment by Mqxx** [comment]
Still persistent in latest Deno version (`v2.1.1`)

**Comment by nounder** [comment]
Same on 2.1.2. I wasted few hours trying to fix it today :(

**Comment by ije** [comment]
some types from esm.sh are broken by the issue too.

```ts
declare module 'highlight.js/private' {
   // ...
}
declare module 'https://esm.sh/highlight.js@11.9.0/types/index.d.ts' {
    import { KeywordDict } from "highlight.js/private";
    // ...
}
```

error output:

```txt
error: Relative import path "highlight.js/private" not prefixed with / or ./ or ../
```

-
Deno **2.1.4**

**Comment by nayeemrmn** [comment]
Fixed by #27631.

**Comment by ch99q** [comment]
<img width="1456" alt="Image" src="https://github.com/user-attachments/assets/52339790-b6c3-4795-8ff2-7fe662b5d34d" />

This is still an issue, the `deno-ts` overrides when it finds a `jsx/tsx` module.
