### ISSUE TITLE
`node:http2` doesn't export `Http2ServerRequest` and `Http2ServerResponse`

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#23326]
### Discussed in https://github.com/denoland/deno/discussions/23324

<div type='discussions-op-text'>

<sup>Originally posted by **OnielN14** April 11, 2024</sup>
In the v1.42.2 I see latest compat update for node http2 is released. So I just try to run hono + @hono/node-server

```ts
import { serve } from "npm:@hono/node-server"
import { Hono } from "npm:hono"

const app = new Hono()
app.get("/", (c) => c.text("Hello from server"))

serve({
  fetch: app.fetch,
  port: 3000
}, () => {
  console.log("Running on 3000")
})
```

and it seems `Http2ServerRequest` is not available as named export.
here is the error message
```
error: Uncaught SyntaxError: The requested module 'http2' does not provide an export named 'Http2ServerRequest'
    at <anonymous> (file:///C:/Users/OnielN14/AppData/Local/deno/npm/registry.npmjs.org/@hono/node-server/1.9.1/dist/index.mjs:5:10)
```

am I missing something regarding node compatiblity?

Thanks</div>

**Comment by bartlomieju** [comment]
No particular reason, it's a bug.

**Comment by clemg** [comment]
Just exporting these two classes ([here](https://github.com/denoland/deno/blob/main/ext/node/polyfills/http2.ts#L2169) and [here](https://github.com/denoland/deno/blob/main/ext/node/polyfills/http2.ts#L2397)) won't make it work.
The response [here](https://github.com/denoland/deno/blob/main/ext/http/00_serve.js#L479) is empty

**Comment by jmj0502** [comment]
@bartlomieju Is this issue still open? I mean can I work on this? Is not entirely clear based on your last comment.

If so, I would like to give it a stab c:

**Comment by satyarohith** [comment]
> @bartlomieju Is this issue still open? I mean can I work on this? Is not entirely clear based on your last comment.
> 
> If so, I would like to give it a stab c:

Hi, @jmj0502. Please go ahead.

**Comment by jmj0502** [comment]
@satyarohith cool!


Quick question? Should I work on the implementation describe on the initial consideration of the issue? or are there other changes to be considered for the issue in question? 🤔

**Comment by satyarohith** [comment]
> @satyarohith cool!
> 
> Quick question? Should I work on the implementation describe on the initial consideration of the issue? or are there other changes to be considered for the issue in question? 🤔

A good target is to get the example from [description](https://github.com/denoland/deno/issues/23326#issue-2238489014) working with Deno. Exporting the unavailable methods isn't sufficient to get it working as mentioned [here](https://github.com/denoland/deno/issues/23326#issuecomment-2056651490). I'm not entirely sure what exactly is required to get the example to work with Deno. We need to explore why the response is empty and what needs to be done.
The scope of it has increased after https://github.com/denoland/deno/issues/23326#issuecomment-2056651490 and I don't think it's a good first issue anymore. But I'm happy to help (You can send me Discord DM) if you're interested to dig deeper. :)

**Comment by jmj0502** [comment]
> A good target is to get the example from https://github.com/denoland/deno/issues/23326#issue-2238489014 working with Deno. Exporting the unavailable methods isn't sufficient to get it working as mentioned https://github.com/denoland/deno/issues/23326#issuecomment-2056651490. I'm not entirely sure what exactly is required to get the example to work with Deno. We need to explore why the response is empty and what needs to be done.
The scope of it has increased after https://github.com/denoland/deno/issues/23326#issuecomment-2056651490 and I don't think it's a good first issue anymore. But I'm happy to help (You can send me Discord DM) if you're interested to dig deeper. :)

@satyarohith Cool! I'm all up for it! Many thanks for offering your help, again I don't really know the codebase in depth, but I'll do my best to fix the issue in question. 

I'll start by building the project and replicating the issue in question, then I'll proceed to send you a discord DM to further explain my plan of action and start diving deeper into the issue. Feel free to assign the issue to me if you consider it appropriate 👍

**Comment by EdamAme-x** [comment]
I also encountered the same issue

**Comment by und-miller** [comment]
I'm also experiencing this issue with the Astro adapter. 

```
PS C:\Users\user.name\Source\project\packages\web\frontend> npm run build  

> frontend@0.1.0 build
> astro build

The requested module 'node:http2' does not provide an export named 'Http2ServerResponse' at file:///C:/Users/user.name/Source/project/node_modules/.deno/astro@4.16.3/node_modules/astro/dist/vite-plugin-astro-server/response.js:1:10
  Stack trace:
    at async runCommand (file:///C:/Users/user.name/Source/project/node_modules/.deno/astro@4.16.3/node_modules/astro/dist/cli/index.js:146:25)
npm error Lifecycle script `build` failed with error:
npm error code 1
npm error path C:\Users\user.name\Source\project\packages\web\frontend
npm error workspace frontend@0.1.0
npm error location C:\Users\user.name\Source\project\packages\web\frontend
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c astro build
PS C:\Users\user.name\Source\project\packages\web\frontend> 
```

**Comment by satyarohith** [comment]
@und-miller what deno version are you using? can you upgrade to the latest version and try again?

**Comment by bartlomieju** [comment]
@und-miller make sure you're using the latest Deno release. This problem was fixed just a few weeks ago.

**Comment by und-miller** [comment]
Thank you for the quick reply. I was indeed running an older version of Deno. After upgrading the problem went away.

**Comment by diecodev** [comment]
This bug is still happening on gh actions. latest version of deno and same problem.
<img width="902" alt="image" src="https://github.com/user-attachments/assets/9eae5d45-cfc8-4522-bfec-93f17b8a2e5e" />
<img width="541" alt="image" src="https://github.com/user-attachments/assets/a6c1f772-bba0-4da9-a214-3b1f30bc680e" />
> [!NOTE]
> I'm using @hono/node-server, and this error is happening on gh action.
