### ISSUE TITLE
`deno compile` fails to download `denort` in 1.45.3

### ISSUE THREAD

**Issue by losfair** [denoland/deno#24719]
Version: Deno 1.45.3

```
$ export https_proxy=http://...
$ deno compile test.ts
Compile file:///path/to/test.ts to test
error: Writing temporary file 'test.tmp-3f1c3003c2ddd4f4'

Caused by:
    0: client error (SendRequest)
    1: invalid HTTP version parsed
```

It worked with Deno 1.45.2.

**Comment by bartlomieju** [comment]
It was fixed in https://github.com/denoland/deno/pull/24696.

**Comment by shuizhongyueming** [comment]
Still facing same problem with Deno 1.45.4

With 
macOS: 14.5
Deno: 1.45.4

env:
http_proxy: http://127.0.0.1:6152
https_proxy: http://127.0.0.1:6152
all_proxy: socks5://127.0.0.1:6153

```
$ deno compile test.ts
Check file:///path/to/test.ts
Compile file:///path/to/test.ts to test
error: Writing temporary file 'test.tmp-fea593cdf8e17bce'

Caused by:
    0: client error (SendRequest)
    1: invalid HTTP version parsed
    
    
$ deno upgrade
Looking up latest version
error: client error (SendRequest)

Caused by:
    invalid HTTP version parsed
```

And 1.45.2 works in my environment.
