### ISSUE TITLE
lib.dom.ts types create LSP errors on hover

### ISSUE THREAD

**Issue by guy-borderless** [denoland/deno#24720]
Version: Deno 1.45.3
In a project with:
```json
{
  "compilerOptions": {
    "lib": ["dom"]
  },
}
```
when viewing the types in `/asset/lib.dom.d.ts`
multiple errors are thrown on hover.
![1721915410](https://github.com/user-attachments/assets/dc338577-2d83-468f-94ec-05c0c0cf4bd6)

```
Unable to get document highlights from TypeScript: tsc error: Error: Could not find source file: 'asset:///lib.dom.d.ts'.
    at getValidSourceFile (ext:deno_tsc/00_typescript.js:149077:22)
    at Object.getDocumentHighlights (ext:deno_tsc/00_typescript.js:149493:24)
    at serverRequest (ext:deno_tsc/99_main_compiler.js:1319:42)
    at serverMainLoop (ext:deno_tsc/99_main_compiler.js:1174:9)
    at eventLoopTick (ext:core/01_core.js:168:7)
For request: [13740, "getDocumentHighlights", ["asset:///lib.dom.d.ts",1306903,["asset:///lib.dom.d.ts"]], null, null]
[Error - 16:46:32] Request textDocument/documentHighlight failed.
  Message: Internal error
  Code: -32603 
```

**Comment by dsherret** [comment]
Duplicates https://github.com/denoland/deno/issues/24608

**Comment by dsherret** [comment]
Should be fixed in canary

**Comment by guy-borderless** [comment]
> Should be fixed in canary

I guess you meant 1.45.6 but just in case, still happens with 1.45.5
![image](https://github.com/user-attachments/assets/881592d9-422a-408d-b06e-9cbe73389356)

**Comment by anthonyg56** [comment]
Im having this issue as well in vscode.

settings
```
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true,
}
```

LSP Output:
```
Starting Deno language server...
  version: 1.46.3 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\devga\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.93.0
Enabling import suggestions for: https://deno.land
Refreshing configuration tree...
  Resolved Deno configuration file: "file:///C:/Users/devga/Documents/Coding/Typescript/Deno/practice/todo_Server/deno.json"
  Resolved lockfile: "file:///C:/Users/devga/Documents/Coding/Typescript/Deno/practice/todo_Server/deno.lock"
Server ready.
Enabling import suggestions for: https://deno.land
Refreshing configuration tree...
  Resolved Deno configuration file: "file:///C:/Users/devga/Documents/Coding/Typescript/Deno/practice/todo_Server/deno.json"
  Resolved lockfile: "file:///C:/Users/devga/Documents/Coding/Typescript/Deno/practice/todo_Server/deno.lock"
Enabling import suggestions for: https://deno.land
Refreshing configuration tree...
  Resolved Deno configuration file: "file:///C:/Users/devga/Documents/Coding/Typescript/Deno/practice/todo_Server/deno.json"
  Resolved lockfile: "file:///C:/Users/devga/Documents/Coding/Typescript/Deno/practice/todo_Server/deno.lock"
successfully cancelled request with ID: 88
Failed to request to tsserver tsc error: Error: Could not find source file: 'asset:///lib.deno.net.d.ts'.
    at getValidSourceFile (ext:deno_tsc/00_typescript.js:149077:22)
    at Object.getEncodedSemanticClassifications3 [as getEncodedSemanticClassifications] (ext:deno_tsc/00_typescript.js:149615:77)
    at serverRequest (ext:deno_tsc/99_main_compiler.js:1319:42)
    at serverMainLoop (ext:deno_tsc/99_main_compiler.js:1174:9)
    at eventLoopTick (ext:core/01_core.js:175:7)
For request: [48, "getEncodedSemanticClassifications", ["asset:///lib.deno.net.d.ts",{"start":0,"length":19172},"2020"], null, null]
[Error - 10:37:07 PM] Request textDocument/semanticTokens/full failed.
  Message: Invalid request
  Code: -32600 
Failed to request to tsserver tsc error: Error: Could not find source file: 'asset:///lib.deno.net.d.ts'.
    at getValidSourceFile (ext:deno_tsc/00_typescript.js:149077:22)
    at Object.getApplicableRefactors2 [as getApplicableRefactors] (ext:deno_tsc/00_typescript.js:150092:18)
    at serverRequest (ext:deno_tsc/99_main_compiler.js:1319:42)
    at serverMainLoop (ext:deno_tsc/99_main_compiler.js:1174:9)
    at eventLoopTick (ext:core/01_core.js:175:7)
For request: [49, "getApplicableRefactors", ["asset:///lib.deno.net.d.ts",{"pos":208,"end":208},{"quotePreference":"auto","includeCompletionsForModuleExports":true,"includeCompletionsForImportStatements":true,"includeCompletionsWithSnippetText":true,"includeAutomaticOptionalChainCompletions":true,"includeCompletionsWithInsertText":true,"includeCompletionsWithClassMemberSnippets":true,"includeCompletionsWithObjectLiteralMethodSnippets":true,"useLabelDetailsInCompletionEntries":true,"allowIncompleteCompletions":true,"importModuleSpecifierPreference":"shortest","importModuleSpecifierEnding":"index","allowTextChangesInNewFiles":false,"providePrefixAndSuffixTextForRename":true,"provideRefactorNotApplicableReason":true,"jsxAttributeCompletionStyle":"auto","includeInlayParameterNameHints":"none","includeInlayParameterNameHintsWhenArgumentMatchesName":false,"includeInlayFunctionParameterTypeHints":false,"includeInlayVariableTypeHints":false,"includeInlayVariableTypeHintsWhenTypeMatchesName":false,"includeInlayPropertyDeclarationTypeHints":false,"includeInlayFunctionLikeReturnTypeHints":false,"includeInlayEnumMemberValueHints":false,"autoImportFileExcludePatterns":[]},"implicit",""], null, null]
[Error - 10:37:08 PM] Request textDocument/codeAction failed.
  Message: Invalid request
  Code: -32600 
Failed to request to tsserver tsc error: Error: Could not find source file: 'asset:///lib.deno.net.d.ts'.
    at getValidSourceFile (ext:deno_tsc/00_typescript.js:149077:22)
    at Object.getEncodedSemanticClassifications3 [as getEncodedSemanticClassifications] (ext:deno_tsc/00_typescript.js:149615:77)
    at serverRequest (ext:deno_tsc/99_main_compiler.js:1319:42)
    at serverMainLoop (ext:deno_tsc/99_main_compiler.js:1174:9)
    at eventLoopTick (ext:core/01_core.js:175:7)
For request: [53, "getEncodedSemanticClassifications", ["asset:///lib.deno.net.d.ts",{"start":0,"length":1042},"2020"], null, null]
[Error - 10:37:08 PM] Request textDocument/semanticTokens/range failed.
  Message: Invalid request
  Code: -32600 
```
