### ISSUE TITLE
deno.kv listener not working anymore

### ISSUE THREAD

**Issue by uriva** [denoland/deno#25934]
I'm seeing tasks being submitted successfully, but an error message occurs afterwards:

```
Error: txnproxy call timed out
file:///src/src/index.ts:37:3
    at async doAtomicWriteInPlace (ext:deno_kv/01_db.ts:628:10)
    at async Kv.enqueue (ext:deno_kv/01_db.ts:163:26)
    at async ext:deno_http/00_serve.ts:364:18
```

code:

```ts
import { pipe, sideLog } from "gamla";

const kv = await Deno.openKv();

kv.listenQueue(
  (x) => {
    console.log("test queue working", x); // this log never appears
  },
);

Deno.serve(
  pipe(
    (x: Request) => x.json(),
    (payload) => kv.enqueue(sideLog(payload)), // this log works, and seems fine
    (_) => new Response(null, { status: 200 }),
  ),
);
```

**Comment by uriva** [comment]
fixed by the team

**Comment by MerryOscar** [comment]
I am still seeing this error on Deno v2.1.2 

```
Error: txnproxy call timed out
    at async doAtomicWriteInPlace (ext:deno_kv/01_db.ts:629:10)
    at async Kv.enqueue (ext:deno_kv/01_db.ts:163:26)
```

@uriva any ideas?

**Comment by uriva** [comment]
Probably should ask the team :)

**Comment by johndevor** [comment]
Still seeing this.
