### ISSUE TITLE
Web Workers use 7x more memory than in Chrome, and terminating them doesn't remove all the memory (i.e. there's a memory leak of some kind)

### ISSUE THREAD

**Issue by josephrocca** [denoland/deno#26058]
Version: Tested in Deno `1.46.x` and `2.x`

If you run this in Chrome, it takes about 150mb of memory, whereas it takes about 1GB for the 100 workers in Deno:
```js
let workers = [];
for(let i = 0; i < 100; i++) {
  const workerBlob = new Blob([`
    delete globalThis.Deno;
    self.onmessage = async function(e) {
      self.postMessage('Hello from Worker!');
    }
  `], { type: 'application/javascript' });
  
  const workerURL = URL.createObjectURL(workerBlob);
  
  let options = {type:"module"};
  if(globalThis.Deno) options.deno = {permissions:"none", namespace:false};
  const worker = new Worker(workerURL, options);
  
  worker.onmessage = function(e) {
    console.log('Received from worker:', e.data);
  };
  
  worker.postMessage('Hello from main thread!');
  workers.push(worker);
}
```
If you then terminate them with the code below, the memory drops back down to the original amount in Chrome, whereas in Deno there is about 300MB of memory still kept around for some reason:
```
for(let w of workers) w.terminate();
workers = [];
```
And note that the amount of memory kept around scales with the number of workers. For example, if you start 200 workers, then there's about 600MB of memory still used after deletion.

**Comment by Hajime-san** [comment]
Maybe this could be related about memory usage.

- https://github.com/denoland/deno/issues/11561#issuecomment-894762539

> I think the slowdown is a combo of the byte array copy in op_postmessage and Deno.core.serialize and Deno.core.deserialize being seperate calls.

**Comment by nathanwhit** [comment]
I believe the cause of the increased memory usage is due to us not being able to enable shared RO heap in V8 (the reason is rather complicated, but once V8 fixes the issue we'll be able to enable it). So where chrome has one copy of globals shared across all isolates, we have a copy per isolate. The globals take up about 7-8MB, which would account for much of the extra memory.

Not sure about the memory not being freed, though

**Comment by josephrocca** [comment]
@nathanwhit Thanks for your comment! I've investigated this a bit further, and it looks like the "leaked" memory actually maxes out at about 500mb, no matter how many workers are created+destroyed, so this may actually be expected behavior - i.e. due to some sort of reuse resource pool, or something. This is a non-issue for me, so unless you suspect this is buggy behavior, I think this aspect can be considered wontfix.

RE the "shared RO heap", I'm looking forward to that. Do you know of any v8 crbug or Deno issue/pull request that I can subscribe to for updates?

**Comment by nemosmithasf** [comment]
Wanted to add volume to this: I also experience memory leaking from large amounts of workers being created/destroyed

**Comment by josephrocca** [comment]
Hey @nathanwhit, just wondering if V8 has been able to fix the "shared RO heap" issue you mentioned yet? Workers are still about 7x larger than Chrome, and 5x larger than Bun 😔

Regarding the 'leak' issue: After testing again on latest version, it still doesn't release the RSS after all workers are terminated, which gradually climbs to 2.4GB after about 10k workers created and terminated, but then it seems to stops there. It's still flatlining at 2.4GB after 100k iterations (and stays at 2.4GB even when all workers are terminated). So it's still an issue (unless this is expected behavior for some reason), but the endless gradual memory leak seems to be gone.

**Comment by bartlomieju** [comment]
@josephrocca I believe most of this should now be addressed by https://github.com/denoland/deno/pull/31375 which should be live as of Deno v2.6.0. Do you want to give it another go?

**Comment by lourd** [comment]
I just upgraded my service that repeatedly spawns and terminates workers to 2.6.1 and it appears it's still having the memory leak. This is a chart of the RAM usage over the last 12 hours

<img width="1468" height="517" alt="Image" src="https://github.com/user-attachments/assets/0df083c5-4f82-475e-acfa-ab2eb673a61a" />

Here's what it looks like over 30 days

<img width="1474" height="422" alt="Image" src="https://github.com/user-attachments/assets/d857f57c-9b65-42da-8294-7ee0318911af" />

You see the pods hitting the memory limit and getting recycled by the scheduler

**Comment by bartlomieju** [comment]
@lourd do you have a reproduction that you could share with us?

**Comment by josephrocca** [comment]
@bartlomieju The minimal reproduction I shared in the original post should work fine if you're just trying to replicate the "leaks until 2.4GB" issue.

I just tried it with latest Deno version for an hour and it got to a bit over 2GB RSS:

```json5
{
  rss: 2233462784,
  heapTotal: 18747392,
  heapUsed: 12104560,
  external: 3296996
}
```

**Comment by bartlomieju** [comment]
Hey folks! Can you try again on Deno v2.7.5? I did some work in #32617 that should improve the situtaion.

**Comment by lourd** [comment]
Hey @bartlomieju, just upgraded my service to 2.7.11 and am still seeing the leak 🫤 

<img width="1492" height="600" alt="Image" src="https://github.com/user-attachments/assets/1dcd846b-d3df-40b0-8188-d43452f09c55" />

I went ahead and made a simplified repro of my service and wrote a test script that confirmed the leak. It's in the repo here https://github.com/lourd/deno-worker-memory-leak-repro

Please let me know if I can provide or test anything else. Thanks for your efforts 🙏

**Comment by bartlomieju** [comment]
Fix PR: #33200

Root cause: `uv_loop_t` (the libuv-compat event loop struct in `deno_core`) had no `Drop` implementation. Each Web Worker allocates a `uv_loop_t` via `uv_loop_init`, which heap-allocates a `UvLoopInner` (~9 KB of HashMaps, BTreeSets, Vecs with pre-allocated capacity). When the worker's `JsRuntime` was torn down, `OpState::clear()` dropped the `Box<uv_loop_t>` but the raw `internal` pointer to `UvLoopInner` was never freed — `uv_loop_close()` was never called.

The fix adds a `Drop` impl that frees the inner allocation. Verified with macOS `leaks` tool: 93% reduction in leaked bytes per worker. RSS now plateaus after warmup instead of growing linearly.

**Comment by lourd** [comment]
Fantastic, thank you @bartlomieju!

**Comment by josephrocca** [comment]
Testing latest version as of writing (on Ubuntu 22.04.5 LTS):
```
deno 2.7.12 (stable, release, x86_64-unknown-linux-gnu)
v8 14.7.173.7-rusty
typescript 5.9.2
```

I ran this (same as the original code I posted when creating the issue, to be clear):
```js
if(self.Deno) {
  console.log(Deno.memoryUsage());
  setInterval(() => {
    console.log(Deno.memoryUsage());
  }, 1000);
}

while(true) {
  
  let workers = [];
  for(let i = 0; i < 100; i++) {
    const workerBlob = new Blob([`
      delete globalThis.Deno;
      self.onmessage = async function(e) {
        self.postMessage('Hello from Worker!');
      }
    `], {type:"application/javascript"});

    const workerURL = URL.createObjectURL(workerBlob);
    const worker = new Worker(workerURL, {type:"module"});

    worker.onmessage = function(e) {
      URL.revokeObjectURL(workerURL);
      console.log('Received from worker:', e.data);
    };
    worker.postMessage('Hello from main thread!');

    workers.push(worker);
  }

  await new Promise(r => setTimeout(r, 5*1000));

  for(let w of workers) w.terminate();
  workers = [];

}
```

And it climbed up to ~2GB RSS within a few minutes, and then I left it running overnight, it eventually crashed (after I think more than 12 hours) with this:
```
...
Received from worker: Hello from Worker!
Received from worker: Hello from Worker!
{
  rss: 3098439680,
  heapTotal: 101634048,
  heapUsed: 96883776,
  external: 3763279
}

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 2.7.12
Args: ["deno"]

View stack trace at:
https://panic.deno.com/v2.7.12/x86_64-unknown-linux-gnu/[unsure if the full version of this URL is meant to be shared privately, i was unaware of the telemetry actually, lmk if you need it]

thread 'worker-349372' (1386212) panicked at ext/io/lib.rs:275:47:
called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
But it's possible that `await new Promise(r => setTimeout(r, 5*1000));` was not enough time to kill all the workers, so they accumulated or something. That seems unlikely though, and it seems strange that it climbs to >2GB RSS very quickly but then climbs slowly from there over 12+ hours.


So I tried this instead (just 10 loops):
```js
if(self.Deno) {
  console.log(Deno.memoryUsage());
  setInterval(() => {
    console.log(Deno.memoryUsage());
  }, 1000);
}

let numLoops = 0;
while(numLoops < 10) {
  numLoops++;
  
  let workers = [];
  for(let i = 0; i < 100; i++) {
    const workerBlob = new Blob([`
      delete globalThis.Deno;
      self.onmessage = async function(e) {
        self.postMessage('Hello from Worker!');
      }
    `], {type:"application/javascript"});

    const workerURL = URL.createObjectURL(workerBlob);
    const worker = new Worker(workerURL, {type:"module"});

    worker.onmessage = function(e) {
      URL.revokeObjectURL(workerURL);
      console.log('Received from worker:', e.data);
    };
    worker.postMessage('Hello from main thread!');

    workers.push(worker);
  }

  await new Promise(r => setTimeout(r, 5*1000));

  for(let w of workers) w.terminate();
  workers = [];

}

await new Promise(r => setTimeout(r, 60*60*1000));
```

Then memory rises very quickly:
```
{
  rss: 155172864,
  heapTotal: 91799552,
  heapUsed: 91069584,
  external: 3770601
}
{
  rss: 1872056320,
  heapTotal: 94031872,
  heapUsed: 91551424,
  external: 3780239
}
{
  rss: 2019532800,
  heapTotal: 95866880,
  heapUsed: 91991256,
  external: 3780553
}
{
  rss: 2237927424,
  heapTotal: 92196864,
  heapUsed: 91190776,
  external: 3705967
}
{
  rss: 2274131968,
  heapTotal: 94031872,
  heapUsed: 91763800,
  external: 3711967
}
{
  rss: 2304901120,
  heapTotal: 95604736,
  heapUsed: 93234656,
  external: 3723989
}
```

And then when loop finishes, it drops down to ~660MB RSS and stays around that amount:
```
{
  rss: 659136512,
  heapTotal: 93769728,
  heapUsed: 92700240,
  external: 3712779
}
```
So it doesn't release all the memory for some reason. I'm unsure if that's expected behavior - I figure it could be holding onto some memory on purpose due to how the allocator works.

I tried letting the while loop go up to numLoops==100, and it did the same thing, but settled down to 786MB RSS.

The "persistent" RSS both when running in the repl and when running with `deno run -A test.js`.
