### ISSUE TITLE
Deno panic: read only DENO_DIR/node_analysis_cache_v2 

### ISSUE THREAD

**Issue by hsjobeki** [denoland/deno#26747]
Version: Deno 2.0.0

I have a read only DENO_DIR which contains all dependencies. It seems Deno needs some writeable `node_analysis_cache_v2` during runtime and panics if it is not writeable. I think it should not be required to be writeable since this locks out execution on all read only file systems. 

I also tried setting `--no-code-cache` which didn't help at all.

Expected behavior:
- Deno runs on all filesystems without trying to modify it. Given that all dependencies are already cached.

This is a blocking my usage because the process is not allowed to write to disk. (As deno by itself has as --allow-write concept)

Log output:

```
Could not initialize cache database '/nix/store/3vkd6102kfkx5mn7z8w864b3kkw21adl-icon-update/lib/.deno/node_analysis_cache_v2', deleting and retrying... (unable to open database file: /nix/store/3vkd6102kfkx5mn7z8w864b3kkw21adl-icon-update/lib/.deno/node_analysis_cache_v2

Caused by:
    Error code 14: Unable to open the database file)
Failed to open cache file '/nix/store/3vkd6102kfkx5mn7z8w864b3kkw21adl-icon-update/lib/.deno/node_analysis_cache_v2', opening in-memory cache.
Could not initialize cache database '/nix/store/3vkd6102kfkx5mn7z8w864b3kkw21adl-icon-update/lib/.deno/dep_analysis_cache_v2', deleting and retrying... (unable to open database file

Caused by:
    Error code 14: Unable to open the database file)
Failed to open cache file '/nix/store/3vkd6102kfkx5mn7z8w864b3kkw21adl-icon-update/lib/.deno/dep_analysis_cache_v2', opening in-memory cache.
Download ⢿ [00:00]
 - jsr:@std/dotenv/meta.json 0.80KiB/0.80KiB



============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 2.0.0
Args: ["/nix/store/sgnh1xzg1r9wjrra26mcfxbcms5x6fzk-deno-2.0.0/bin/deno", "run", "--allow-env", "--allow-net", "--allow-read", "--allow-write", "--no-code-cache", "/nix/store/3vkd6102kfkx5mn7z8w864b3kkw21adl-icon-update/bin/icon-update"]

thread 'main' panicked at /build/deno-2.0.0-vendor.tar.gz/deno_cache_dir/src/global/mod.rs:116:6:
called `Result::unwrap()` on an `Err` value: Custom { kind: ReadOnlyFilesystem, error: "Read-only file system (os error 30) (for '/nix/store/3vkd6102kfkx5mn7z8w864b3kkw21adl-icon-update/lib/.deno/remote/https/jsr.io/6e93eacee453ae985c9af5b017821e0621908a939b7f2e0907574bba27c31ed0')" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by littledivy** [comment]
[Fixed](https://github.com/denoland/deno_cache_dir/commit/39d2a509137942fc12a93ae3a7124c14436523ea) in latest Deno 2.0.5 (`deno upgrade`)

**Comment by hsjobeki** [comment]
@littledivy

My script runs now. But i still get this big warning is there some cli flag to disable the node_analysis_cache_v2 at all ?

```
$ deno --version
deno 2.0.5 (stable, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2
```

```
Could not initialize cache database '/nix/store/nxyfv2z1r0kmdsdcs1wrfgzhd7q8irib-deps/.deno/node_analysis_cache_v2', deleting and retrying... (unable to open database file: /nix/store/nxyfv2z1r0kmdsdcs1wrfgzhd7q8irib-deps/.deno/node_analysis_cache_v2

Caused by:
    Error code 14: Unable to open the database file)
Failed to open cache file '/nix/store/nxyfv2z1r0kmdsdcs1wrfgzhd7q8irib-deps/.deno/node_analysis_cache_v2', opening in-memory cache.
Could not initialize cache database '/nix/store/nxyfv2z1r0kmdsdcs1wrfgzhd7q8irib-deps/.deno/dep_analysis_cache_v2', deleting and retrying... (attempt to write a readonly database

Caused by:
    Error code 8: Attempt to write a readonly database)
Failed to open cache file '/nix/store/nxyfv2z1r0kmdsdcs1wrfgzhd7q8irib-deps/.deno/dep_analysis_cache_v2', opening in-memory cache.
...
# Script runs
```

**Comment by hsjobeki** [comment]
Made https://github.com/denoland/deno/pull/26807
Help with registering the flag is highly appreciated.
