### ISSUE TITLE
deno compile cross-compilation to macOS fails with "program not found" in v2.6.0 (regression from v2.5.6)

### ISSUE THREAD

**Issue by mcgear** [denoland/deno#31675]
## Summary

Cross-compiling to macOS targets (`x86_64-apple-darwin`, `aarch64-apple-darwin`) from Windows fails in Deno 2.6.0 with "I/O error: program not found". This worked correctly in Deno 2.5.6.

## Version

- **Broken:** Deno 2.6.0
- **Works:** Deno 2.5.6

## Platform

Windows 10/11 x64 (also reproducible on Ubuntu GitHub Actions runners)

## Reproduction

```bash
# Any project with npm dependencies (e.g., esbuild, zod)
deno compile --target x86_64-apple-darwin -o test ./main.ts

**Comment by bartlomieju** [comment]
Already fixed in https://github.com/denoland/deno/pull/31587 and released in V2.6.1.

**Comment by mcgear** [comment]
I still receive this same error with 2.6.1


error: Writing deno compile executable to temporary file 'G:\Fathym\source\github\fathym-deno\fathym-dev-space\projects\open-source\fathym-cli\.dist\exe\x86_64-apple-darwin\ftm.tmp-be846823e0a3457d'      

Caused by:
    0: Writing binary bytes
    1: I/O error: program not found {"cliName":"Fathym CLI","cliVersion":"0.0.0","commandKey":"$Command","levelHint":"error"}
✖ ❌ deno command failed with exit code 1 {"cliName":"Fathym CLI","cliVersion":"0.0.0","commandKey":"$Command","levelHint":"error"}

G:\Fathym\source\github\fathym-deno\fathym-dev-space>deno
Deno 2.6.1

**Comment by mcgear** [comment]
I know a lot of that is specific to our CLI, sorry, this is probably the important bit:

x86_64-apple-darwin
Caused by:
0: Writing binary bytes
1: I/O error: program not found

**Comment by bartlomieju** [comment]
We're releasing v2.6.3 right now that should include a fix for it, please try later on latest version and let me know if this was fixed, looks like the error from https://github.com/denoland/deno/issues/31664

**Comment by bartlomieju** [comment]
Deno v2.6.3 is now released that shouldn't have this problem.

**Comment by sobanieca** [comment]
I wonder if my release isn't failing because of this issue even on 2.6.3... https://github.com/sobanieca/jsonr/actions/runs/20397837739/job/58615864022#step:5:154

**Comment by sobanieca** [comment]
Yes, I've switched to 2.5 and release is fine there. It seems there is still an issue with macos compilation...

**Comment by bartlomieju** [comment]
We'll fix it after New Year

**Comment by Matzu89** [comment]
> Yes, I've switched to 2.5 and release is fine there. It seems there is still an issue with macos compilation...

Lock and load - `v2.x` -> `v2.5`

Merry Christmas and a Happy New Year!
