### ISSUE TITLE
Unhandled promise rejections are confusing

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#4879]
When there are unhandled promise rejections, when they are logged, they look just like unhandled throws, but they are different and should be noted as different.

For example, in the REPL:

```
> Promise.reject(new Error("boo"));
Promise {
 <rejected> Error: boo
    at <unknown>:1:16
    at evaluate ($deno$/repl.ts:64:34)
    at Object.replLoop ($deno$/repl.ts:153:13)
}
error: Uncaught Error: boo
    at <unknown>:1:16
    at evaluate ($deno$/repl.ts:64:34)
    at Object.replLoop ($deno$/repl.ts:153:13)
```

**Comment by nayeemrmn** [comment]
Trying on an older version, it looks like `"Uncaught Error: boo"` is precisely the message we get from `v8::Exception::create_message()`.

At the moment we have a custom code path where, if the error is a JS Error Object, we construct this message ourselves and the "Uncaught" is added manually. Even if we added guards for that, `Promise.reject(1)` still gives `Uncaught 1` from V8.

**Comment by JustFly1984** [comment]
Is it possible to create cross issue in v8 repo?

**Comment by kitsonk** [comment]
Chrome produces the following:

```
Uncaught (in promise) Error: boo
    at <anonymous>:1:16
```

**Comment by caspervonb** [comment]
As of my rewrite we only get

```
Promise { <rejected> Error: boo
    at <anonymous>:2:16 }
```

**Comment by bartlomieju** [comment]
@caspervonb thanks for checking, I think this issue is resolved.

**Comment by nayeemrmn** [comment]
It's not resolved, there's actually a new bug where async errors in the repl don't bubble to the top:
```
> const p = Promise.reject();
undefined
> ...
```

**Comment by caspervonb** [comment]
Hmm, seems like we don't have the wiring to catch that.

Should be able to hook into this notification but it is never fired.

https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-exceptionThrown

**Comment by nayeemrmn** [comment]
Also to be clear about the original issue, we just want `Uncaught Error: ...` to instead be `Uncaught (in promise) Error: ...` when printing the error at termination.

**Comment by caspervonb** [comment]
REPL behavior remains the same here, so probably best to leave this open

**Comment by nayeemrmn** [comment]
Let's track that in #8858, since this was about `(in promise)` indicators for rejections.
