### ISSUE TITLE
Errors in dynamic imports are not properly caught

### ISSUE THREAD

**Issue by shynome** [denoland/deno#6259]
Runtime
```
debian 10
deno 1.6.2
v8 8.8.278.2
typescript 4.1.3
```
------

```ts
//a.ts
import("./b.ts").catch(e=>{
  console.log("caught import b.ts error")
  console.error(e)
})

import("./c.ts").catch(e=>{
  console.log("caught import c.ts error")
  console.error(e)
})

setInterval(function () {
  import("./c.ts").catch((e) => {
    console.log("caught interval import c.ts error");
    console.error(e);
  });
}, 1e3);
```
```ts
//b.ts
// @ts-ignore
import "./b1.ts";
export default () => "error";
```
```ts
//c.ts
// @ts-ignore
await import("./c1.ts");
export default () => "error";
```

create those files and then run `deno run -A a.ts`, you will get log like below:
```
caught import b.ts error
TypeError: Cannot resolve module "file://yourdir/b1.ts" from "file://yourdir/b.ts".
    at file://yourdir/b.ts:3:0
caught import c.ts error
TypeError: Cannot resolve module "file://yourdir/c1.ts".
error: Uncaught TypeError: Cannot resolve module "file://yourdir/c1.ts".
```

`import('./c.ts')` first error is caught, but then second import is not caught and it make my program exit

**Comment by shynome** [comment]
it works in node v14, so I think there is something wrong, I will try to find it out

the test command is `node --harmony-top-level-await a.mjs`, before test you need rename `.ts` to `.mjs`

**Comment by bartlomieju** [comment]
Just tried on latest `master`

```
▶ target/debug/deno run --allow-read a.ts
caught import b.ts error
TypeError: Cannot resolve module "file:///Users/biwanczuk/dev/deno/b1.ts" from "file:///Users/biwanczuk/dev/deno/b.ts"
Imported from "file:///Users/biwanczuk/dev/deno/b.ts:3"

caught import c.ts error
TypeError: Cannot resolve module "file:///Users/biwanczuk/dev/deno/c1.ts" from "file:///Users/biwanczuk/dev/deno/c.ts"

error: Uncaught TypeError: Cannot resolve module "file:///Users/biwanczuk/dev/deno/c1.ts" from "file:///Users/biwanczuk/dev/deno/c.ts"
```

This is still broken

**Comment by shynome** [comment]
so sad, this is still not working

**Comment by bartlomieju** [comment]
```
~/dev/deno  master
▶ deno run --allow-read=. a.mjs
error: Cannot resolve module "file:///Users/biwanczuk/dev/deno/c1.mjs" from "file:///Users/biwanczuk/dev/deno/c.mjs".
    at file:///Users/biwanczuk/dev/deno/c.mjs:3:6

~/dev/deno  master
▶ node --harmony-top-level-await a.mjs
caught import b.mjs error
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/biwanczuk/dev/deno/b1.mjs' imported from /Users/biwanczuk/dev/deno/b.mjs
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
caught import c.mjs error
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/biwanczuk/dev/deno/c1.mjs' imported from /Users/biwanczuk/dev/deno/c.mjs
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at Loader.import (internal/modules/esm/loader.js:164:28)
    at importModuleDynamically (internal/modules/esm/translators.js:99:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at file:///Users/biwanczuk/dev/deno/c.mjs:3:1
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Looks like a problem with catching errors in dynamic imports. I will look into that

**Comment by kitsonk** [comment]
Some of the fixes that are out there may impact this @bartlomieju.

**Comment by bartlomieju** [comment]
@kitsonk I did more investigating and the problem originates from `module_graph.rs` - when V8 starts loading `a.mjs` (which is an entry point) a module graph is constructed during `prepare_module_load` callback. Module graph eagerly tries to fetch dynamically imported modules and fails either on `c1.mjs` or `b1.mjs` resulting in error. This error is forwarded to `prepare_module_load` which causes V8 to return error for loading main module. I think module graph shouldn't return error in such case, though it might be way more complex problem than in the hind sight (mostly because of TLA). Thoughts?

**Comment by kitsonk** [comment]
Yeah, this is complicated, on a couple levels...

- The module graph tries to eagerly fetch dynamic imports and its dependencies, where if we swallow the error from the file fetcher, it then causes
- program_state panics when source files cannot be provided to the module loader in core.

Ultimately we need to do a bit of refactoring so that the module graph better handles "gaps" in the graph due to missing dependencies without erroring or a panic, and that we serve up modules to the core loader in a more logical way that doesn't panic.  I had a not in there about refactoring `fetch_compiled_module` as ideally that should be coming from the module_graph, which is more aware of the state, but we also need the module graph to gracefully handle "missing" dependencies, which it doesn't quite do at the moment.

So this is a bit more complex than I expected, and will have to spend some more time on it.

**Comment by shynome** [comment]
dynamic import error still make program exit
add a new file `s.ts`, then run it `deno run -A s.ts`, the program is exit after import ./a.ts
```ts
import { serve } from "https://deno.land/std/http/server.ts";
const s = serve({ port: 0 });

setTimeout(() => {
  import("./a.ts").catch((err) => 0);
}, 1e3);

for await (const req of s) {
  // 
}
```

**Comment by kitsonk** [comment]
@shynome I cannot reproduce this.  What version of Deno are you using?

**Comment by shynome** [comment]
I run it in debian docker image, still get the same error
```log
deno 1.6.2 (release, x86_64-unknown-linux-gnu)
v8 8.8.278.2
typescript 4.1.3
```
`deno run -A s.ts`
```log
Download https://deno.land/std/http/server.ts
Warning Implicitly using latest version (0.82.0) for https://deno.land/std/http/server.ts
Download https://deno.land/std@0.82.0/http/server.ts
Download https://deno.land/std@0.82.0/_util/assert.ts
Download https://deno.land/std@0.82.0/http/_io.ts
Download https://deno.land/std@0.82.0/io/bufio.ts
Download https://deno.land/std@0.82.0/async/mod.ts
Download https://deno.land/std@0.82.0/encoding/utf8.ts
Download https://deno.land/std@0.82.0/async/delay.ts
Download https://deno.land/std@0.82.0/async/pool.ts
Download https://deno.land/std@0.82.0/async/deferred.ts
Download https://deno.land/std@0.82.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.82.0/textproto/mod.ts
Download https://deno.land/std@0.82.0/http/http_status.ts
Download https://deno.land/std@0.82.0/bytes/mod.ts
Check file:///app/s.ts
Check file:///app/a.ts
Check file:///app/b.ts
Check file:///app/c.ts
caught import b.ts error
TypeError: Cannot resolve module "file:///app/b1.ts" from "file:///app/b.ts".
    at file:///app/b.ts:3:0
caught import c.ts error
TypeError: Cannot resolve module "file:///app/c1.ts".
error: Uncaught (in promise) TypeError: Cannot resolve module "file:///app/c1.ts".

```

**Comment by kitsonk** [comment]
Ah  I misunderstood the repro. Ok, it seems we fixed one issue but it uncovered another. The uncaught promise in c.mjs is terminating the process. @bartlomieju it seems that we need to investigate the correct behaviour of uncaught TLA rejections?

**Comment by nayeemrmn** [comment]
Smaller repro:
```ts
try {
  await import(`data:application/typescript;base64,${btoa(`await new Promise(r => setTimeout(r, 100)); throw new Error("foo");`)}`);
  // The rejection causes an exception before being caught here.
} catch (error) {
  console.trace(error, "--");
}
```

It occurs because this line: https://github.com/denoland/deno/blob/5873adeb5e6ec2113eeb5adc964b7ce129d4905d/core/runtime.rs#L814 attempts to remove the promise from the list of exceptions _before_ it is ever added by this line: https://github.com/denoland/deno/blob/5873adeb5e6ec2113eeb5adc964b7ce129d4905d/core/bindings.rs#L284-L286 so it is never removed. For modules with "truly" async top levels, the first one is run after the promise is returned while the second is run after it rejects. Fix coming.

**Comment by shynome** [comment]
hi, I have try the new version and I found it just catch the first async import error, then the second async import error still not be caught and make program crash

**Comment by nayeemrmn** [comment]
Smaller repro again:
```ts
try {
  await import("./cli/tests/error_001.ts");
} catch {}

try {
  await import("./cli/tests/error_001.ts");
} catch {}
```

It's a completely separate error that occurs when you try to dynamically import a module that previously rejected. It propagates as a sync error in the event loop. Fix coming.

**Comment by caramboleyo** [comment]
just upgraded to 1.30.0
deno is still not passing the trace properly to the catch block.
trace ends at the import statement, no clue where inside the import an error happened.
(in my case unexpected reserved word, forgot async in front of a function where i used await)

**Comment by bartlomieju** [comment]
@caramboleyo can you provide a reproduction code?

**Comment by caramboleyo** [comment]
https://github.com/caramboleyo/deno-topfen

**Comment by caramboleyo** [comment]
@bartlomieju also think about dyamic import of a dynamic import of a dynamic import and so on.
