### ISSUE TITLE
Uncaught BrokenPipe: Broken pipe (os error 32)  

### ISSUE THREAD

**Issue by ITS-NIGHTOWL** [denoland/deno#6319]
After running my ws client for 11 hours, I got this error (for the first time):
```
error: Uncaught BrokenPipe: Broken pipe (os error 32)   
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.write ($deno$/ops/io.ts:65:18)
    at async BufWriter.flush (https://deno.land/std@0.54.0/io/bufio.ts:479:25)
    at async writeFrame (https://deno.land/std@0.54.0/ws/mod.ts:144:3)
```
Any reasons as to why?

**Comment by wongjiahau** [comment]
I'm also getting this error, but for different reasons

**Comment by bartlomieju** [comment]
Please provide more reproduction. `Broken pipe` might happen for number of reasons, eg. the other side of connection closes it abruptly.

**Comment by colorhook** [comment]
WebSocket demo reload web page and deno server exit

And I cannot caught the exception

```
async function dispatch(msg: string): Promise<void> {
  for (const client of clients.values()) {
    try {
      await client.send(msg)
    } catch (err) {}
  }
}
``

```
Uncaught BrokenPipe: Broken pipe (os error 32)   
    at unwrapResponse (rt/10_dispatch_minimal.js:52:13)
    at sendAsync (rt/10_dispatch_minimal.js:95:12)
    at async write (rt/12_io.js:117:20)
    at async Object.writeAll (rt/13_buffer.js:223:19)
    at async BufWriter.flush (bufio.ts:467:7)
    at async writeFrame (mod.ts:141:3)
```

deno version

```
deno 1.2.0
v8 8.5.216
typescript 3.9.2
```

**Comment by Caesar2011** [comment]
I get this error when starting a localhost webserver with `for await (const req of server) {` and then open a tab in Firefox from yesterday.

Probably the browser tries to use the previous connection and the server crashes because the connection is unknown.

**Comment by lmiller1990** [comment]
I get this error after around 24h - my server serves HTML at about 30-60 request / h. Basically the "hello world" like setup, no extra dependencies. I am on deno 1.3.x.

**Comment by erf** [comment]
I also experienced a similar error message on Deno 1.4 and 1.5. I have a http / websocket server which also serve some static files using `serveFile`. The crash happens at startup when i load the `index.html`, creates a web socket connection and serve a set of static files, with the `favicon.ico` last. I added the `favicon.ico` after i got a message that it was missing, but i wonder if the crashes started after that.. The crashes only happens a couple of times, and then it seem to work fine for a while, until i get a crash again.

Here is the log:

```
% ./run.sh
http://localhost:8080/
... loading various js files ..
my_project/public/some.js
my_project/public/favicon.ico
error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32)
    at unwrapResponse (deno:cli/rt/10_dispatch_minimal.js:59:13)
    at sendAsync (deno:cli/rt/10_dispatch_minimal.js:98:12)
    at async write (deno:cli/rt/12_io.js:117:20)
    at async BufWriter.write (bufio.ts:498:29)
    at async Object.copy (deno:cli/rt/12_io.js:38:23)
    at async writeResponse (_io.ts:278:15)
    at async ServerRequest.respond (server.ts:84:7)
```

Here is a minimal example:

``` TypeScript
const server = serve({ port: port })
console.log(`http://localhost:${port}/`)

for await (const req of server) {

    // serve index page
    if (req.url === '/') {
        req.respond({
            status: 200,
            body: await Deno.open('./public/index.html')
        })
    }
    // accept the websocket connection
    else if (req.url === '/ws') {
        if (!acceptable(req)) {
            throw new Error('Not acceptable web socket connection.');
        }
        acceptWebSocket({
            conn: req.conn,
            bufReader: req.r,
            bufWriter: req.w,
            headers: req.headers,
        }).then(wsConnection)
    }
    // or server static content
    else {
        const path = `${Deno.cwd()}/public${req.url}`
        console.log(path)
        try {
            const content = await serveFile(req, path)
            req.respond(content)
        } catch (e) {
            console.log(e)
        }
    }
}
```

**Comment by rvdende** [comment]
Running into this as well.. about 12 hours after starting the service. Might be that the client changed ip addresses and that confused deno or something like that? Also Deno error message doesn't tell me where in my code the issue originated from.

```js
error: Uncaught BrokenPipe: Broken pipe (os error 32)
    at unwrapResponse (deno:cli/rt/10_dispatch_minimal.js:59:13)
    at sendAsync (deno:cli/rt/10_dispatch_minimal.js:98:12)
    at async write (deno:cli/rt/12_io.js:117:20)
    at async BufWriter.write (bufio.ts:499:29)
    at async writeResponse (_io.ts:273:15)
    at async ServerRequest.respond (server.ts:84:7)
    at async Response.end (response.ts:218:5)

```

**Comment by LeonardGreulich** [comment]
Same problem here. Very frequently after a few hours of running (between 6 and 12 hours I guess).

```JavaScript
error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32)
    at unwrapResponse (deno:cli/rt/10_dispatch_minimal.js:59:13)
    at sendAsync (deno:cli/rt/10_dispatch_minimal.js:98:12)
    at async write (deno:cli/rt/12_io.js:117:20)
    at async Object.writeAll (deno:cli/rt/13_buffer.js:223:19)
    at async BufWriter.flush (bufio.ts:468:7)
    at async writeResponse (_io.ts:288:3)
    at async Server.iterateHttpRequests (server.ts:154:11)
    at async Server.acceptConnAndIterateHttpRequests (server.ts:227:5)
    at async MuxAsyncIterator.callIteratorNext (mux_async_iterator.ts:30:31)
```

**Comment by LeonardGreulich** [comment]
Has anyone found a workaround for this? i.e., catching the error or restarting the server after the error occurs?

For me, Deno is currently unusable because of this, unfortunately ...

**Comment by rvdende** [comment]
Closest I font to a workaround is to switch to http and run a nginx reverse proxy with the certificate/key infront of deno

**Comment by LeoGreuli** [comment]
Thanks for the suggestion!

However, this already is my configuration and Deno crashes even when using http only.

**Comment by bartlomieju** [comment]
Errors originating from HTTP server should be fixed by https://github.com/denoland/deno/pull/8365

**Comment by timonson** [comment]
This `BrokenPipe: Broken pipe (os error 32)` error still happens with std `0.82.0` all the time using Firefox, not so much on Chrome.

Please reopen this issue!

>BrokenPipe: Broken pipe (os error 32)
    at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:59:13)
    at sendAsync (deno:runtime/js/10_dispatch_minimal.js:98:12)
    at async write (deno:runtime/js/12_io.js:117:20)
    at async Object.writeAll (deno:runtime/js/13_buffer.js:223:19)
    at async BufWriter.flush (bufio.ts:468:7)
    at async writeResponse (_io.ts:288:3)
    at async ServerRequest.respond (server.ts:84:7)
