### ISSUE TITLE
deno bundle config file bug?

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#6384]
I have come across a bug during ```deno bundle``` during fetching deps.
Can it be that Deno doesn't apply the specified config file on fetched files?

### Project
- root
  - tsconfig.json

```json
// tsconfig.json
{
  "compilerOptions": {
    "noImplicitAny": true
  }
}
```

## Reproduction

```sh
deno bundle --config tsconfig.json https://dev.jspm.io/webscript > webscript.js
```

As a comparison – This works as expected:
```sh
deno bundle https://dev.jspm.io/lit-element > lit-element.js
```

### Expected Behavior
fetches and bundles the files.

### Actual Behavior
results in an error:

```
error: TS7006 [ERROR]: Parameter 'element' implicitly has an 'any' type.
function addChild(element, child) {
                  ~~~~~~~
    at https://dev.jspm.io/npm:webscript@1.0.2/webscript.js:3:19
```

The ```noImplicitAny```is specifically set in ```tsconfig.json```.
Any ideas on why this happens?

**Comment by kitsonk** [comment]
`"noImplicitAny": true` means you cannot have implicit any, so the behaviour is as expected. 😕 Changing it to `"noImplicitAny": false` produces other errors not related to implicit any.

I am concerned though that the compiler is checking JavaScript without that being part of the config. @bartlomieju

**Comment by bartlomieju** [comment]
@timreichen could you try again with `v1.1.1`, I think it might have been fixed in https://github.com/denoland/deno/pull/6304

**Comment by timreichen** [comment]
Nope, still throws errors:
It complained about the libs so

```json
// tsconfig.json
{
  "compilerOptions": {
    "noImplicitAny": false,
    "lib": ["dom", "ESNext"]
  }
}
```
then
```sh
deno bundle --config tsconfig.json https://dev.jspm.io/webscript > webscript.js

Bundling https://dev.jspm.io/webscript

error: TS2683 [ERROR]: 'this' implicitly has type 'any' because it does not have a type annotation.
    let { props, prop } = this.__element_info__;
                          ~~~~
    at https://dev.jspm.io/npm:webscript@1.0.2/webscript.js:64:27

TS2683 [ERROR]: 'this' implicitly has type 'any' because it does not have a type annotation.
    let { props: existingProps } = this.__element_info__;
                                   ~~~~
    at https://dev.jspm.io/npm:webscript@1.0.2/webscript.js:69:36
```

for some weird reason the ```js``` file has ```// @ts-check``` on line 1. So even when 
```json
{
  "compilerOptions": {
    "noImplicitAny": false,
    "lib": ["dom", "ESNext"],
    "allowJs": true,
    "checkJs": false
  }
}
```
it will check and then throws. I tested it without ```// @ts-check``` and it succeeded. So I guess ```// @ts-check``` overwrites ``` "checkJs": false```?
Is this a ```ts```or a ```deno bundle``` problem? Maybe a ```deno bundle --nocheck```or something in that manner would help?

**Comment by kitsonk** [comment]
Correct, `// @ts-check` would always override `"checkJs": false`.  That is a TypeScript compiler behaviour and not something we can control.

`deno bundle` does not allow overriding the `lib` files, as its main purpose is to generate bundles that run in Deno, and the built in types contain all the DOM library APIs that Deno supports, where as `Deno.bundle()` does as it is designed for creating bundles for other workloads.

So effectively, this is "working as designed" I am afraid.
