### ISSUE TITLE
Possible broken test case "responseFormData"

### ISSUE THREAD

**Issue by lowlighter** [denoland/deno#8069]
Hi,
I'm currently working on a #8063 to make assertions handle `symbols` correctly, but it seems to reveal a broken test case.

The test in question is [`responseFormData`](https://github.com/denoland/deno/blob/master/cli/tests/unit/response_test.ts#L40-L51) which is below :
```ts
unitTest(async function responseFormData() {
  const input = new FormData();
  input.append("hello", "world");
  const response = new Response(input, {
    headers: { "content-type": "application/x-www-form-urlencoded" },
  });
  const formDataPromise = response.formData();
  assert(formDataPromise instanceof Promise);
  const formData = await formDataPromise;
  assert(formData instanceof FormData);
  assertEquals(formData, input);
});
```

It fails with the following result when using `symbol` checks :
```diff
AssertionError: Values are not equal:
    [Diff] Actual / Expected
    FormData {
      [Symbol(data)]: [
        [
-         "[object FormData]",
-         "",
+         "hello",
+         "world",
        ],
      ],
    }
```

With `Deno.inspect` , `input` returns `FormData { [Symbol(data)]: [ [ "hello", "world" ] ] ` while `formData` returns `FormData { [Symbol(data)]: [ [ "[object FormData]", "" ] ] }` (like if the formData was casted to string mistakenly).

My guess is that since data are indexed with a `symbol` instead of a regular key, the `assertEquals` was actually ignoring it (because it uses `for (const key in object)` which doesn't include symbols).

It could possibly mean that `response.formData()` or this test case is actually broken.

**Comment by kitsonk** [comment]
It looks like a bad test... comparing `FormData` what way doesn't make any sense, and your change highlighted that it "wrong".

**Comment by lucacasonato** [comment]
Whoops. That is my doing. Should be fixed relatively easily by replacing the last assert with
```ts
  assertEquals([...formData.entries()], [...input.entries()]);
```

**Comment by lowlighter** [comment]
> Whoops. That is my doing. Should be fixed relatively easily by replacing the last assert with
> 
> ```ts
>   assertEquals([...formData.entries()], [...input.entries()]);
> ```

It doesn't seem to work because the value of `[...formData.entries()]` is actually `[ [ "[object FormData]", "" ] ]` so it'll still throws on the assertion. Not sure why it ended up like this though.

**Comment by lucacasonato** [comment]
Interesting. Looks like a bug in our `Body::formData` method. I will investigate.

**Comment by ariain** [comment]
hey @lucacasonato , I would like to give this issue a try, can I work on it??

**Comment by lucacasonato** [comment]
Sure. I looked into this a few days ago, and it looks more complicated than I initially expected. But feel free to give it a shot.

**Comment by ariain** [comment]
@lucacasonato thanks...

**Comment by ariain** [comment]
@lowlighter can you tell what command you used to test these test cases...

**Comment by lowlighter** [comment]
> @lowlighter can you tell what command you used to test these test cases...

You can checkout on #8063 to test.

Basically I attempted to run the unit test I provided earlier with `Deno.test` but for debugging you can just copy-paste the code and add a `console.log([...formData.entries()], [...input.entries()])` before the assertion, it should be enough to check whether you fixed it or not.

I tried to fix it when I encoutered this error but I reckon that I had no clue from where to start so that's why I opened this issue x)

**Comment by ariain** [comment]
Hi @lucacasonato , I was testing this code and is it necessary here to send the header in Response params in following code??
```
const temp = async () => {
  const input = new FormData();
  input.append("hello", "world");
  const response = new Response(input, {
    headers: { "content-type": "application/x-www-form-urlencoded" },
  });
  const formDataPromise = response.formData();
  const formData = await formDataPromise;
  console.log(...input.entries());
  console.log(...formData.entries());
};

temp();
```

I am asking this because the data in console is 
```
["hello", "world"]
```
```
["------WebKitFormBoundaryCoOAzj6Jc8KdKUPk
Content-Disposition: form-data; name", "'hello'

world
------WebKitFormBoundaryCoOAzj6Jc8KdKUPk--
"]
``` 

I think this is the problem here...

**Comment by lucacasonato** [comment]
Are you running this in Deno?

**Comment by ariain** [comment]
I ran this in browser actually..

**Comment by ariain** [comment]
Ran in deno and got 
```
[ "hello", "world" ]
```
```
[ "[object FormData]", "" ]
```

**Comment by ariain** [comment]
@lucacasonato "good first bug" tag shouldn’t be here in this issue...

**Comment by ariain** [comment]
@lucacasonato should there any difference between values from chrome and deno??

**Comment by ariain** [comment]
Hi @lucacasonato and @lowlighter , I tried to look into this but its too complex for me as I am a beginner in open source. Please look into this. I believe the code needed is here somewhere...
https://github.com/denoland/deno/blob/c4d33e8d778aa1b86197f1c54ff8e4e61a2ebf53/op_crates/fetch/26_fetch.js#L406-L491
Also I checked working of `append` function in this and its working fine...

**Comment by lucacasonato** [comment]
Great analysis! I think instead of taking the branch that leads to `.toString` in `bodyToArrayBuffer`, we should be doing the same thing that happens in the `fetch` implementation here: https://github.com/denoland/deno/blob/c4d33e8d778aa1b86197f1c54ff8e4e61a2ebf53/op_crates/fetch/26_fetch.js#L1236-L1246

Its unfortunate that this is going to duplicated code, but we will address that soon when we refactor `fetch` to enable streaming uploads.

**Comment by lowlighter** [comment]
@lucacasonato Do you have some leads to patch this ?

**Comment by lowlighter** [comment]
Seems resolved
