### ISSUE TITLE
Uncaught TypeError when running bundle created with Deno 1.5.2

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#8302]
See output:

```
example % cat example.ts
export {DB, Empty, Status} from 'https://deno.land/x/sqlite@v2.3.1/mod.ts';

example % deno run example.ts 
Check file:///Users/jesse/example/example.ts

example % deno bundle example.ts example.bundle.js
Bundle file:///Users/jesse/example/example.ts
Check file:///Users/jesse/example/example.ts
Emit "example.bundle.js" (826.41KB)

example % deno run example.bundle.js              
error: Uncaught TypeError: Cannot read property 'Null' of undefined
const Empty = new Rows(null, Values.Null);
                                    ^
    at file:///Users/jesse/example/example.bundle.js:449:37

```

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by bartlomieju** [comment]
Fixed in #8443

**Comment by vegidio** [comment]
I'm still having a problem (deno 1.6.0 (release, x86_64-apple-darwin))

The code below works with I run `deno run --allow-net test.ts`:

This is the content of the file:

```typescript
import axiod from 'https://deno.land/x/axiod/mod.ts';
const url = 'http://hn.algolia.com/api/v1/search?query=javascript';
axiod.get(url)
    .then((result) => console.log(result.data));
```

However, if I create a bundle `deno bundle test.ts out.js`,
and try to run this bundle `deno run --allow-net out.js`
I get the error below:

```
error: Uncaught TypeError: axiod.request is not a function
    return axiod.request(Object.assign({
                 ^
    at Function.axiod.get (file:///Users/vegidio/Desktop/test/out.js:81:18)
    at file:///Users/vegidio/Desktop/test/out.js:161:7
```

**Comment by kdy1** [comment]
I checked it and I verified that axiod is properly handled.
@vegidio It seems like the patch is not published yet.

**Comment by kitsonk** [comment]
@vegidio 1.6.2 is the current release.

**Comment by vegidio** [comment]
@kitsonk Thanks. I had Deno installed originally from Homebrew and the version there is still 1.6.0.

However I just uninstalled that version and I installed 1.6.2 through the shell script `curl -fsSL https://deno.land/x/install/install.sh | sh`, but this version also has the same bug.

Any idea what version will have the fix for this bug and when that is going to be released?
