### ISSUE TITLE
`deno compile` does not have dynamic import support

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#8655]
This is a tracking issue to investigate how we can support dynamic import in `deno compile`, and what the use cases would be.

**Comment by iaincollins** [comment]
If it helps, as a module maintainer a use case I've had for dynamic imports in NPM packages to only load modules when needed (e.g. depending on options passed in by whatever is consuming the module) - i.e. to load things regarded "optional peer dependencies" at runtime, such as drivers for a specific database. Not supporting dynamic imports causes problems for applications that use the relatively small number of modules that depend on this feature.

It turns out lack of dynamic import support is also a problem for some other build tools and in certain run time environments.

Users ended up reporting issues with the dependency on dynamic imports, so much so I looked around for other options and found [require_optional](https://github.com/christkv/require_optional) which is a little known package but used by the [mongodb driver](https://jira.mongodb.org/browse/NODE-1749). IIRC it comes with it's own issues though, as it assumes package.json exists (and I seem to recall doesn't currently behave nicely if it doesn't) so it provides an ugly solution of sorts, at least for maintainers.

Outside of modules I'm not sure of a good use case that absolutely needs dynamic imports - as there are other ways to do conditional includes at build time - but as a library maintainer I don't think there is another way around the problem of having a range of optional peer dependencies, at least not short of publishing multiple modules (or at least multiple entrypoints in a module).

In the uses cases I've had, converting them to standard imports would work (if that is possible?) but I'm not sure if hosting them would have side effects in some packages because I don't know off hand what the differences are between behaviour of `import` and `require` is (if dynamic `import` statements cache like `require` does presumably doing that would be fine unless they were doing something shady like looking for env vars that are not set until some point at runtime?).

**Comment by danielr1996** [comment]
> Outside of modules I'm not sure of a good use case that absolutely needs dynamic imports - as there are other ways to do conditional includes

I might have a use case, but I'm not entirely sure that there aren't alternatives. I'm currently developing a cli application that can be extended with plugins, instead of using a json file that contains the name of the plugins to load you can just `import` a plugin from a url or write your own plugin or debugging code inline with the config, very much like webpack and rollup do it with their config files. 

Besides that dynamic imports are defined in the ES2015 spec and therefore IMHO it should be supported regardless of the possible use cases.

**Comment by andreespirela** [comment]
@lucacasonato We could support dynamic imports with Base64 modules

**Comment by shadowtime2000** [comment]
Yeah I agree with @andreespirela it may be better to just support base64 modules so like in the example of @danielr1996 you could instead just use file system APIs to read the file and then convert to base64 and then dynamically import it.

**Comment by kitsonk** [comment]
The problem with data URL modules at the moment is that we decode them and write them to the Deno cache, so it isn't just like we can twiddle a couple knobs and have them work.  The thing with compile is that the JavaScript bundle is "all" the code needed, with no external references outside of that JavaScript modules, which then allows us to be able to load that single module into the compiler, all the code that does dependency analysis, and ability to convert and cache resources is stripped out in the "thin binary" that is used by compile.

**Comment by axetroy** [comment]
Since dynamic import can splice desired strings, it is difficult to perform static analysis.

So, we should think about how to solve it from another angle

I think this can be resolve by https://github.com/tc39/proposal-import-assertions

```ts
// Pack the typescript file into binary as plain string
import code from "./foo.ts" assert { type: "plaintext" };

// Dynamic execute the code
await import(`data:base64,${btoa(code)}`)
```

**Comment by nayeemrmn** [comment]
> I think this can be resolve by https://github.com/tc39/proposal-import-assertions
> 
> ```ts
> // Pack the typescript file into binary as plain string
> import code from "./foo.ts" assert { type: "plaintext" };
> 
> // Dynamic execute the code
> await import(`data:base64,${btoa(code)}`)
> ```

We already came to terms with the fact that dynamic imports aren't meant for reliable static analysis, ever since we unsupported the best-effort behaviour that existed with tsc's bundler. IMO it's much better to leave it at that and never attempt any static resolution of dynamic imports. So in compiled executables, dynamic imports = runtime module loading.

**Comment by andreespirela** [comment]
@nayeemrmn Are import assertions already in V8? If so, are they coming in Deno 1.8?

**Comment by shadowtime2000** [comment]
@andreespirela Yeah, I believe import assertions are coming in Deno 1.8 because right now they are parsed but they are ignored.

**Comment by shadowtime2000** [comment]
Maybe this should be marked with the "compile" label?

**Comment by rivy** [comment]
I'd love to be able to use `denon` as a stand-alone utility or another `deno`-similar variant (with full `deno` capabilities) as a cross-platform task runner or specialized script runner (eg, similar to `perl -ne ...`). Being able to produce such completely stand-alone variant executables would be an *extremely* attractive quality for devs.

**Comment by iugo** [comment]
file-system router needs dynamic import.

- https://nextjs.org/docs/routing/introduction
- https://nuxtjs.org/docs/2.x/features/file-system-routing/

**Comment by yujong-lee** [comment]
Any update on this? It seems like #13563 does not solve this yet.

**Comment by bartlomieju** [comment]
> Any update on this? Our team need dynamic import in Deno binary.

No update. What is your use case?

**Comment by yujong-lee** [comment]
@bartlomieju 

We are using `deno compile` to binary package a code-generator. The code-generator also allows for customization - user can add their own code to the base generated code.

## 1
The code-generator is designed to work over two passes.
1. Generates the base code. (user can make customizations)
2. Integrates the user provided extension code into the module.

The second pass dynamically imports the user code and further generates boiler-plate code. (SDK/API end-points, documentation etc).

This is not currently possible without the dynamic import capability in the deno compile generated binary.

## 2

A second use-case is to use the binary as a domain-specific REPL, over the functionality of the generated+customized code. Basically, load the generated module, and allow for convenience commands over a REPL (auto-completion and more).

---
In both these cases, we'd be happy to take responsibility for correctness of the imported code - idea being to run type-checker/transpiler or similar on the imported code to ensure correctness before attempting the dynamic import. That is specifically not a concern for us.

A resolution would be much appreciated.

**Comment by varHarrie** [comment]
I built a [sandbox module](https://github.com/varHarrie/simple_sandbox/blob/master/worker.ts#L6), and also encountered this problem.

**Comment by mweichert** [comment]
I just wanted to add that we have a use-case too.

We have a CLI utility we're using that generates configuration files in TypeScript, and then load these files at runtime. Looks similiar to https://github.com/varHarrie/simple_sandbox

The utility uses `deno compile` to create an executable.

The error emitted is `TypeError: Module not found`.

**Comment by spion** [comment]
Another usecase for a configuration generator here: reimplementing [jkcfg](https://jkcfg.github.io/) on top of Deno for built-in typescript type checking support.

**Comment by brundonsmith** [comment]
To add a use-case: I'm building a compiler in Deno that outputs JavaScript. I want to ship the toolchain as a standalone executable, but for things like running tests it needs to be able to interpret the JavaScript code that it generates. I would really like to avoid requiring the user to install a separate JavaScript runtime for such features

**Comment by lordanubi** [comment]
I think this is essential, browsers already have support for dynamic imports

**Comment by borkdude** [comment]
I'm having an issue with `deno bundle` and dynamic imports. My Clojure interpreter [bebo](https://github.com/borkdude/bebo) which runs on deno uses dynamic import. 

Example:

foo.js:

``` javascript
import { runScript } from 'https://cdn.jsdelivr.net/npm/bebo@0.0.6/lib/bebo_core.js'

// import "https://deno.land/std@0.146.0/http/server.ts"

await runScript(Deno.args[0]);
```

foo.cljs:
``` clojure
(ns foo
  (:require
   ["https://deno.land/std@0.146.0/http/server.ts" :as server]))

(def port 8080)

(defn handler [req]
  (let [agent (-> req .-headers (.get "user-agent"))
        body (str "Your user agent is: " (or agent
                                             "Unknown"))]
    (new js/Response body #js {:status 200})))

(server/serve handler #js {:port port})
```

Compile:

```
deno compile --allow-all -o /tmp/foo /tmp/foo.js /tmp/foo.cljs
```

Run:

```
$ /tmp/foo
error: Uncaught (in promise) TypeError: Module not found
await runScript(Deno.args[0]);
^
    at async file:///tmp/foo.js:5:1
```

When I uncomment:

``` javascript
// import "https://deno.land/std@0.146.0/http/server.ts"
```

in `foo.js, then the compiled bundle works.

So perhaps it would be useful to have the compile option support a list of imports  that should be preserved, or maybe there is already such a feature?

**Comment by cowboyd** [comment]
Adding our use-case is a CLI with

1.  plugin system
2. inspect user supplied values (`graphgen inspect path/to/your/custom/setup.ts`)

**Comment by cowboyd** [comment]
> The problem with data URL modules at the moment is that we decode them and write them to the Deno cache, so it isn't just like we can twiddle a couple knobs and have them work. The thing with compile is that the JavaScript bundle is "all" the code needed, with no external references outside of that JavaScript modules, which then allows us to be able to load that single module into the compiler, all the code that does dependency analysis, and ability to convert and cache resources is stripped out in the "thin binary" that is used by compile.

@kitsonk What is the advantage of having a "thin" binary?

**Comment by vectronic** [comment]
It would be good if this gap was documented explicitly in these locations to avoid more people ending up needing to +1 this ticket...

* https://deno.land/manual@v1.25.2/introduction#feature-highlights
* https://deno.land/manual@v1.25.2/tools/compiler

**Comment by cowboyd** [comment]
For the use-case of implementing plugins for a CLI, would it make sense to be able to exercise some type of control over the import map used in the dynamically imported module? If the plugin wanted to use its own import map, or you wanted to isolate it completely from the imports of the main executable, this would feel desirable. For that matter, allowing plugins to have some control over how they are executed via a configuration, would be nice as well E.g.

```ts
const moduleEnv = createModuleEnv({
  importMap: '/path/to/plugin/import-map.json',
  configurationFile: '/path/to/plugin/deno.json',
  allow: ['env', 'read'],
})

const module = moduleEnv(() => import('/path/to/plugin/mod.ts'));
```

**Comment by cowboyd** [comment]
For those coming here looking for a workaround, one option is to dynamically load plugins as CommonJS packages using `createRequire()`, which works quite well. It's not ideal to have plugins be constrained to being npm packages, and I hope that there is a better way to do it in the future, but at least for our use-case and for the time being, it's better than nothing.

**Comment by alcuadrado** [comment]
CLIs with js-based config also need this feature

**Comment by RichiCoder1** [comment]
I have the same use case of .js configs as well as runtime-loadable plugins.

**Comment by dsherret** [comment]
Deno 1.31 added support for statically analyzable dynamic imports: https://deno.com/blog/v1.31#deno-compile-works-with-statically-analyzable-dynamic-imports

Deno 1.32 (releasing later this month) will add support for web workers (https://github.com/denoland/deno/commit/090169cfbc6699486765b729d532b5b837210b12) and the ability to specify non-analyzable modules to include in the binary (https://github.com/denoland/deno/commit/b64ec7926831896f4e43b685891111409de45e85)

**Comment by RichiCoder1** [comment]
Should a new ticket be spun up now? It doesn't sound like any of the above features support dynamic import of modules _not_ available at compile time which was asked for a few times in this thread.

**Comment by dsherret** [comment]
@RichiCoder1 yes, I'd recommend a new targeted issue for that. It will also help it be more easily searchable.

**Comment by alcuadrado** [comment]
> @RichiCoder1 yes, I'd recommend a new targeted issue for that. It will also help it be more easily searchable.

done! thanks for the update

**Comment by rivy** [comment]
Thanks @dsherret!

The committed changes make some headway toward the full dynamic import, but many of the use-cases mentioned in the previous discussion are still not possible to implement.

See <https://github.com/denoland/deno/issues/18327> (thanks to @alcuadrado) for continuation of the issue.
