### ISSUE TITLE
Deno Compile inserts literal \r\n into code base

### ISSUE THREAD

**Issue by jon49** [denoland/deno#8746]
When I compile my scripts I have strings like so

```typescript
html`<p>This is my

HTML</p>`
```

When I compile my scripts into an executable deno turn my string into something like this (I'm assuming):

```typescript
html`<p>This is my\r\n\r\nHTML</p>`
```

Here's what the HTML source code looks like:

```html
\r\n<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n
```

Which cause my web page to have a bunch of literal `\r\n` new line characters peppered throughout.

Here's my original code: https://github.com/jon49/VideoDownloader/blob/ea6e5b29058a421ffa1d1d2ce3cb7a983f1e64fe/src/pages/home/index.html.ts#L26

**Comment by lucacasonato** [comment]
cc @kdy1

**Comment by Liamolucko** [comment]
This should be fixed now thanks to swc-project/swc#1286.

**Comment by bartlomieju** [comment]
@jon49 are you experiencing the problem on 1.6.2?

**Comment by jon49** [comment]
Looks like it didn't fix it :-(

![Source html code in browser](https://user-images.githubusercontent.com/3173098/103027209-a4b53900-4512-11eb-8061-62d02c75d220.PNG)

![What it looks like in the browser.](https://user-images.githubusercontent.com/3173098/103027322-df1ed600-4512-11eb-98be-d7bf76ed17f1.PNG)

**Comment by Liamolucko** [comment]
Whoops, looks like I misunderstood the problem.

Looking at your code some more, though, it looks like the problem is that you're using `literals.raw` - that contains the value **without processing any escape sequences**. Doing this should fix it:
```diff
 // src/util/html.ts
 function* htmlGenerator(literals, ...subs) {
-   var length = literals.raw.length,
+   var length = literals.length,
       s = "",
       escape = true
    for (var i = 0; i < length; i++) {
-      let lit = literals.raw[i]
+      let lit = literals[i]
       let sub = subs[i - 1]
       if (sub) {
          if (Array.isArray(sub)) { for (s of sub) if (s) yield s }
```

This could still be considered a problem, though - replacing newlines with escape sequences _does_ change the behaviour, even if only in a minor way.
