### ISSUE TITLE
Deno bundle produces reference error

### ISSUE THREAD

**Issue by dev-nicolaos** [denoland/deno#9350]
## Environment
- Windows 10 Home version 20H2
- Observed as early as Deno version 1.7.2, still present in 1.9.0

## Steps to reproduce
- Clone the example repo: https://github.com/dev-nicolaos/deno-bundle-bug
- In the repo's top level folder, run `deno run --unstable --import-map=import_map.json mod.ts`
- Observe that the program runs and exits without any errors
- In the repo's top level folder, run `deno bundle --unstable --import-map=import_map.json mod.ts bundle.js`
- In the repo's top level folder, run `deno run bundle.js` (with or without the `--unstable` flag)

## Observed behavior
The program exits with an `Uncaught ReferenceError`

## Expected behavior
The program runs successfully just as it did before it was bundled, and exits without any errors

## Notes
The example repo here is admittedly a bit contrived, I'm having this problem in a much larger project and essentially removed as much of it as I could while still being able to reproduce the error. This has been an issue for at least the last few versions of deno, and the same thing happens when using the `deno compile` command. I've also tried this (in the larger project) on Ubuntu (running on WSL) with the same results.

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by kdy1** [comment]
FIxed on upstream

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/pull/9374

**Comment by dev-nicolaos** [comment]
@bartlomieju @kdy1 I just ran this through the same steps to reproduce with Deno `v1.7.2` and Deno std `v0.86.0`, and it appears the bug is still present. I updated the import map in the example repo.

**Comment by dev-nicolaos** [comment]
My understanding is this has been fixed in swc, but I haven't seen Deno pull in a new version in a while. Any chance the dependency could get bumped before the next release?

**Comment by lucacasonato** [comment]
@dev-nicolaos we updated just before the 1.8 release on tuesday.

**Comment by dev-nicolaos** [comment]
ah, missed it since it was bundled with other upgrades, thanks for pointing it out. Will rerun steps to reproduce on new 1.8.0.

**Comment by dev-nicolaos** [comment]
Bug still present walking through the above steps with Deno v1.8.0 and Deno std 0.89.0 😢

**Comment by dev-nicolaos** [comment]
@kdy1 I just walked through the steps to reproduce again with Deno v1.9.0 and std 0.93.0 since I saw the version of the bundler got bumped, but this still appears to be an issue.

**Comment by kdy1** [comment]
Really fixed on upstream :)

**Comment by dev-nicolaos** [comment]
@bartlomieju @lucacasonato any chance we could see a upgrade to the bundler before the next release? Looks like this and several other bugs (#10112, #10187, #10252) have fixes available in the latest version.

**Comment by bartlomieju** [comment]
We'll update it for 1.9.2 in about a week

**Comment by dev-nicolaos** [comment]
Can confirm, fixed in 1.9.2. Thanks for the all the hard work @kdy1
