### ISSUE TITLE
MultipartReader fails with UnexpectedEof if using --no-check or compille

### ISSUE THREAD

**Issue by vinc3m1** [denoland/deno#9620]
Same issue as #7932, not sure why the author closed that bug.

```
error: Uncaught (in promise) UnexpectedEof
  private isBoundaryDelimiterLine(line: Uint8Array): boolean {
^
    at MultipartReader.nextPart (https://deno.land/std@0.88.0/mime/multipart.ts:413:1)
    at async MultipartReader.readForm (https://deno.land/std@0.88.0/mime/multipart.ts:319:1)
```

I first found this only happening when I compiled my script to a binary (`compile --unstable`).
Then, after finding #7932, I tested `--no-check` and it results in the same error. 

Code works just fine with regular `deno run`

std@0.88.0
deno 1.7.5

**Comment by vinc3m1** [comment]
Not sure if this is a different issue, but I noticed I can get the same/similar error if my multipart text has a trailing newline:

```typescript
import { MultipartReader } from "https://deno.land/std@0.88.0/mime/multipart.ts";
import { StringReader } from "https://deno.land/std@0.88.0/io/readers.ts";


const works = `
--------------------------366796e1c748a2fb
Content-Disposition: form-data; name="payload"
Content-Type: text/plain

CONTENT
--------------------------366796e1c748a2fb--` //no newline at eof

const fails = `
--------------------------366796e1c748a2fb
Content-Disposition: form-data; name="payload"
Content-Type: text/plain

CONTENT
--------------------------366796e1c748a2fb--
` // newline at eof

const boundary = "------------------------366796e1c748a2fb";

const stringReader = new StringReader(works);
const multipartReader = new MultipartReader(stringReader, boundary);
const formData = await multipartReader.readForm() // this works
console.log("formdata", formData);

const stringReader2 = new StringReader(fails);
const multipartReader2 = new MultipartReader(stringReader2, boundary);
const formData2 = await multipartReader2.readForm() // this fails
console.log("formdata2", formData2);
```

**Comment by vinc3m1** [comment]
Filed under deno_std instead, with more details: https://github.com/denoland/deno_std/issues/767

**Comment by vinc3m1** [comment]
It seems that after running with `--no-check`, the broken deps are cached and subsequent runs withouth the `--no-cache` flag still fail, even with `--reload`.

test file:
```typescript
import { MultipartReader } from "https://deno.land/std@0.88.0/mime/multipart.ts";
import { StringReader } from "https://deno.land/std@0.88.0/io/readers.ts";

// carriage returns added for running on POSIX, not needed if on windows
const content = `--------------------------366796e1c748a2fb\r
Content-Disposition: form-data; name="payload"\r
Content-Type: text/plain\r
\r
CONTENT\r
--------------------------366796e1c748a2fb--`

const boundary = "------------------------366796e1c748a2fb";

const stringReader = new StringReader(content);

const multipartReader = new MultipartReader(stringReader, boundary);
const formData = await multipartReader.readForm()
for (const entry of formData.entries()) {
  console.log("entry", entry);
}
console.log("formdata", formData);
```

output:
```
$ deno run test.ts
Check file:///.../test.ts
entry [ "payload", "CONTENT" ]
formdata {
  file: [Function: file],
  value: [Function: value],
  entries: [GeneratorFunction: entries],
  removeAll: [AsyncFunction: removeAll],
  [Symbol(Symbol.iterator)]: [Function: [Symbol.iterator]]
}

$ deno run test.ts
Check file:///.../test.ts
entry [ "payload", "CONTENT" ]
formdata {
  file: [Function: file],
  value: [Function: value],
  entries: [GeneratorFunction: entries],
  removeAll: [AsyncFunction: removeAll],
  [Symbol(Symbol.iterator)]: [Function: [Symbol.iterator]]
}

$ deno run --no-check test.ts
error: Uncaught UnexpectedEof
  private isBoundaryDelimiterLine(line: Uint8Array): boolean {
^
    at MultipartReader.nextPart (https://deno.land/std@0.88.0/mime/multipart.ts:413:1)
    at async MultipartReader.readForm (https://deno.land/std@0.88.0/mime/multipart.ts:319:1)
    at async file:///home/vince/vinc3m1/plexbot/test.ts:16:1

$ deno run test.ts
Check file:///.../test.ts
error: Uncaught UnexpectedEof
  private isBoundaryDelimiterLine(line: Uint8Array): boolean {
^
    at MultipartReader.nextPart (https://deno.land/std@0.88.0/mime/multipart.ts:413:1)
    at async MultipartReader.readForm (https://deno.land/std@0.88.0/mime/multipart.ts:319:1)
    at async file:///home/vince/vinc3m1/plexbot/test.ts:16:18

$ deno run -r test.ts
Download https://deno.land/std@0.88.0/mime/multipart.ts
Download https://deno.land/std@0.88.0/io/readers.ts
Download https://deno.land/std@0.88.0/io/bufio.ts
Download https://deno.land/std@0.88.0/_util/assert.ts
Download https://deno.land/std@0.88.0/_util/has_own_property.ts
Download https://deno.land/std@0.88.0/bytes/mod.ts
Download https://deno.land/std@0.88.0/io/ioutil.ts
Download https://deno.land/std@0.88.0/textproto/mod.ts
Download https://deno.land/std@0.88.0/path/mod.ts
Download https://deno.land/std@0.88.0/path/posix.ts
Download https://deno.land/std@0.88.0/path/separator.ts
Download https://deno.land/std@0.88.0/path/glob.ts
Download https://deno.land/std@0.88.0/path/win32.ts
Download https://deno.land/std@0.88.0/_util/os.ts
Download https://deno.land/std@0.88.0/path/common.ts
Download https://deno.land/std@0.88.0/path/_interface.ts
Download https://deno.land/std@0.88.0/path/_constants.ts
Download https://deno.land/std@0.88.0/path/_util.ts
Check file:///home/vince/vinc3m1/plexbot/test.ts
error: Uncaught UnexpectedEof
  private isBoundaryDelimiterLine(line: Uint8Array): boolean {
^
    at MultipartReader.nextPart (https://deno.land/std@0.88.0/mime/multipart.ts:413:1)
    at async MultipartReader.readForm (https://deno.land/std@0.88.0/mime/multipart.ts:319:1)
    at async file:///home/vince/vinc3m1/plexbot/test.ts:16:18
```

**Comment by kitsonk** [comment]
cc/ @kdy1 I haven't narrowed it down yet, but it looks like there is some problem with the output of transpiling.

**Comment by nayeemrmn** [comment]
I recognise this error, it's what lead me to track down and open https://github.com/swc-project/swc/issues/930. In other words this is #9773 seen in https://github.com/denoland/deno_std/blob/0.90.0/mime/multipart.ts#L264-L269. It will also be fixed by #9774, once we adapt that code to the additional `"useDefineForClassFields"` restrictions.

**Comment by nayeemrmn** [comment]
Fixed by https://github.com/denoland/deno_std/pull/807.

**Comment by vinc3m1** [comment]
While this seems to have fixed the `--no-check` case, the `compile --unstable` case is still broken using the test script linked to in https://github.com/denoland/deno/issues/9620#issuecomment-787210444:
```
$ deno compile --unstable test.ts
[...]
Emit test
$ ./test
error: ReferenceError: matchAfterPrefix is not defined
    at scanUntilBoundary (file://$deno$/bundle.js:1702:9)
    at PartReader.read (file://$deno$/bundle.js:1737:22)
    at async copyN (file://$deno$/bundle.js:107:24)
    at async MultipartReader.readForm (file://$deno$/bundle.js:1825:27)
    at async file://$deno$/bundle.js:2095:18
```

But running with --no-check passes now so that's good:
```
$ deno run --no-check test.ts
entry [ "payload", "CONTENT" ]
formdata {
  file: [Function: file],
  value: [Function: value],
  entries: [GeneratorFunction: entries],
  removeAll: [AsyncFunction: removeAll],
  [Symbol(Symbol.iterator)]: [Function: [Symbol.iterator]]
}
```

**Comment by nayeemrmn** [comment]
@vinc3m1 For tracking purposes, can you open a separate issue for that?

**Comment by bartlomieju** [comment]
Fixed in 1.9.0

**Comment by vinc3m1** [comment]
> @vinc3m1 For tracking purposes, can you open a separate issue for that?

Sure, created a separate issue to track: #10187
