### ISSUE TITLE
deno-lint: Intl is not defined

### ISSUE THREAD

**Issue by lowlighter** [denoland/deno#9896]
[Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) API type definition is missing from `deno lint` though it is a global namespace.

```ts
//test.ts
console.log(new Intl.DateTimeFormat("en-UK", {
  year: "2-digit",
  month: "2-digit",
  day: "2-digit",
  hour: "2-digit",
  minute: "2-digit",
  second: "2-digit",
  fractionalSecondDigits: 3,
}).format(new Date()));
```

Run work as expected:
```
PS ~> deno run test.ts
Check file:///~/test.ts
25/03/21, 22:28:41.794
```

Linter think `Intl` is not defined:
```
PS ~> deno lint --unstable test.ts
(no-undef) Intl is not defined
console.log(new Intl.DateTimeFormat("en-UK", {
                ^^^^
    at ~/test.ts:1:16

Found 1 problem
Checked 1 file
```

Deno version:
```
PS ~> deno --version
deno 1.8.2 (release, x86_64-pc-windows-msvc)
v8 9.0.257.3
typescript 4.2.2
```

**Comment by MierenManz** [comment]
This is should be fixed by this [pr]
(https://github.com/denoland/deno_lint/pull/636)

**Comment by lowlighter** [comment]
https://github.com/denoland/deno_lint/pull/636 is still listed in diff https://github.com/denoland/deno_lint/compare/v0.2.20...main, so I guess it didn't make it in final release yet 😕

It's strange, I checked the dates too and it has been merged 10 days ago but latest release of deno lint is noted as 4 days ago.
Anyway thanks for linking the PR, I'll use `//deno-lint-ignore no-undef` waiting for next release 🙂

**Comment by kitsonk** [comment]
Fixed in #635

**Comment by jsejcksn** [comment]
Should this be reopened since #635 was closed without being merged?

<details>
<summary>I am still seeing this as well.</summary>

```
example % deno lint --unstable main.ts
(no-undef) Intl is not defined
const daysFormatted = new Intl.NumberFormat('en-US').format(Math.round(days));
                          ^^^^
    at /Users/jesse/example/main.ts:24:26

Found 1 problem
Checked 1 file

example % deno --version
deno 1.8.3 (release, x86_64-apple-darwin)
v8 9.0.257.3
typescript 4.2.2
```
</details>

**Comment by nayeemrmn** [comment]
@jsejcksn https://github.com/denoland/deno_lint/pull/636 was meant to be linked. It hasn't released yet.
